from __future__ import annotations

from copy import deepcopy
from typing import Any


DEFAULT_CHANGELOG_LANGUAGE = "zh-CN"
SUPPORTED_CHANGELOG_LANGUAGES = frozenset({"zh-CN", "en-US", "ko-KR", "ru-RU", "ja-JP", "es-ES"})

CHANGELOG_STRUCTURE: tuple[dict[str, Any], ...] = (
    {
        "version": "0.8.8",
        "date": "2026-07-21",
        "entries": (
            (
                "v088_added_title",
                (("feature", "v088_dependency_action"),),
            ),
            (
                "v088_adjusted_title",
                (("improvement", "v088_unit_formation_width"),),
            ),
        ),
    },
    {
        "version": "0.8.7",
        "date": "2026-07-20",
        "entries": (
            (
                "v087_added_title",
                (
                    ("feature", "v087_type_order"),
                    ("feature", "v087_type_sort"),
                    ("feature", "v087_manual_type"),
                ),
            ),
            (
                "v087_adjusted_title",
                (("improvement", "v087_readability"),),
            ),
            (
                "v087_fixed_title",
                (("fix", "v087_publish_modal_ui"),),
            ),
        ),
    },
    {
        "version": "0.8.6",
        "date": "2026-07-19",
        "entries": (
            (
                "v086_fixed_title",
                (
                    ("fix", "v086_playset_dependencies"),
                    ("fix", "v086_settings_page_ui"),
                ),
            ),
        ),
    },
    {
        "version": "0.8.5",
        "date": "2026-07-19",
        "entries": (
            (
                "v085_fixed_title",
                (
                    ("fix", "v085_non_ascii_launch_paths"),
                    ("fix", "v085_game_data_overhauls"),
                    ("fix", "v085_steam_friends_utf8"),
                ),
            ),
        ),
    },
    {
        "version": "0.8.2",
        "date": "2026-07-19",
        "entries": (
            (
                "v082_added_title",
                (
                    ("feature", "v082_batch_ai_generation"),
                    ("feature", "v082_search_highlight"),
                ),
            ),
            (
                "v082_fixed_title",
                (("fix", "v082_ai_highlight_cache"),),
            ),
        ),
    },
    {
        "version": "0.8.1",
        "date": "2026-07-18",
        "entries": (
            (
                "v081_fixed_title",
                (
                    ("fix", "v081_friendly_fire"),
                    ("fix", "v081_game_scoped_playsets"),
                    ("fix", "v081_update_restart"),
                    ("fix", "v081_unit_formation"),
                ),
            ),
        ),
    },
    {
        "version": "0.8.0",
        "date": "2026-07-18",
        "entries": (
            (
                "v080_added_title",
                (
                    ("feature", "v080_three_kingdoms"),
                    ("feature", "v080_shortcuts"),
                    ("feature", "v080_workshop_collection_import"),
                    ("feature", "v080_recruitment_capacity"),
                ),
            ),
            (
                "v080_adjusted_title",
                (
                    ("improvement", "v080_publish_simplified"),
                    ("improvement", "v080_update_channel"),
                    ("improvement", "v080_editable_shortcuts"),
                    ("improvement", "v080_themed_controls"),
                ),
            ),
            (
                "v080_fixed_title",
                (
                    ("fix", "v080_workshop_ownership"),
                    ("fix", "v080_startup_guidance"),
                    ("fix", "v080_recycle_button"),
                    ("fix", "v080_unicode_paths"),
                ),
            ),
        ),
    },
    {
        "version": "0.7.0",
        "date": "2026-07-17",
        "entries": (
            (
                "v070_added_title",
                (
                    ("feature", "v070_single_entity_unit_rule"),
                    ("feature", "v070_workshop_cover"),
                    ("feature", "v070_spanish_language"),
                ),
            ),
            (
                "v070_fixed_title",
                (
                    ("fix", "v070_low_consumption_stability"),
                    ("fix", "v070_unit_scale_ticks"),
                    ("fix", "v070_game_data_patch_reliability"),
                    ("fix", "v070_save_mods"),
                ),
            ),
        ),
    },
    {
        "version": "0.6.5",
        "date": "2026-07-17",
        "entries": (
            (
                "v065_added_title",
                (
                    ("feature", "v065_auto_patch"),
                    ("feature", "v065_unit_scale"),
                    ("feature", "v065_workshop_links"),
                ),
            ),
            (
                "v065_adjusted_title",
                (
                    ("improvement", "v065_game_data_window"),
                    ("improvement", "v065_author_names"),
                ),
            ),
            (
                "v065_fixed_title",
                (
                    ("fix", "v065_skip_intro"),
                ),
            ),
        ),
    },
    {
        "version": "0.6.0",
        "date": "2026-07-16",
        "entries": (
            (
                "v060_added_title",
                (
                    ("feature", "v060_low_consumption"),
                    ("feature", "v060_live_detection"),
                    ("feature", "v060_game_data_controls"),
                    ("feature", "v060_unit_multiplier"),
                    ("feature", "v060_friendly_fire"),
                    ("feature", "v060_save_actions"),
                    ("feature", "v060_select_all"),
                    ("feature", "v060_official_profiles"),
                    ("feature", "v060_copy_path"),
                    ("feature", "v060_safe_delete"),
                ),
            ),
            (
                "v060_adjusted_title",
                (
                    ("improvement", "v060_startup_speed"),
                    ("improvement", "v060_unsubscribe_cleanup"),
                ),
            ),
            (
                "v060_fixed_title",
                (
                    ("fix", "v060_dependency_refresh"),
                    ("fix", "v060_force_update_wait"),
                ),
            ),
        ),
    },
    {
        "version": "0.5.0",
        "date": "2026-07-15",
        "entries": (
            (
                "v050_added_title",
                (
                    ("feature", "v050_settings_pages"),
                    ("feature", "v050_about_page"),
                    ("feature", "v050_restore_last_order"),
                    ("feature", "v050_drag_lists"),
                    ("feature", "v050_publish_language"),
                    ("feature", "v050_change_note"),
                    ("feature", "v050_share_subscribe"),
                    ("feature", "v050_system_language"),
                    ("feature", "v050_builtin_languages"),
                ),
            ),
            (
                "v050_adjusted_title",
                (
                    ("improvement", "v050_button_style"),
                    ("improvement", "v050_single_language_ui"),
                    ("improvement", "v050_enabled_dependency_scope"),
                    ("improvement", "v050_dependency_cache_warning"),
                    ("improvement", "v050_readme"),
                ),
            ),
            (
                "v050_fixed_title",
                (
                    ("fix", "v050_outdated_check"),
                ),
            ),
        ),
    },
    {
        "version": "0.3.0",
        "date": "2026-07-15",
        "entries": (
            (
                "v030_added_title",
                (
                    ("feature", "v030_ignore_issues"),
                    ("feature", "v030_warning_window"),
                ),
            ),
            (
                "v030_fixed_title",
                (
                    ("fix", "v030_data_location"),
                ),
            ),
        ),
    },
    {
        "version": "0.2.0",
        "date": "2026-07-15",
        "entries": (
            (
                "v020_added_title",
                (
                    ("feature", "v020_dual_source"),
                    ("feature", "v020_context_menu"),
                ),
            ),
            (
                "v020_fixed_title",
                (
                    ("fix", "v020_pyinstaller"),
                ),
            ),
        ),
    },
    {
        "version": "0.1.0",
        "date": "2026-07-15",
        "entries": (
            (
                "v010_added_title",
                (
                    ("feature", "v010_playsets"),
                    ("feature", "v010_game_workshop"),
                    ("feature", "v010_updates"),
                ),
            ),
        ),
    },
)



CHANGELOG_TEXT: dict[str, dict[str, str]] = {
    "zh-CN": {
        "v088_added_title": "新增",
        "v088_dependency_action": "缺失依赖警告界面现在可以直接订阅并启用缺失的依赖。",
        "v088_adjusted_title": "调整",
        "v088_unit_formation_width": "调整单位规模倍率后，现在可以将阵型拉得更长。",
        "v087_added_title": "新增",
        "v087_type_order": "类型管理支持调整内置和自定义类型的显示顺序，并会持久保存。",
        "v087_type_sort": "新增按类型排序，使用已配置的类型顺序排列 MOD。",
        "v087_manual_type": "右键菜单新增“手动输入”类型，并支持 Shift+F 快捷键批量应用类型。",
        "v087_adjusted_title": "调整",
        "v087_readability": "放大详情信息、底部操作按钮、类型管理和设置页面等区域的文字，提高可读性。",
        "v087_fixed_title": "修复",
        "v087_publish_modal_ui": "修复发布更新窗口的关闭按钮和文本框大小调整控件样式不一致的问题。",
        "v086_fixed_title": "修复",
        "v086_playset_dependencies": "修复某些情况下依赖检测失效的问题",
        "v086_settings_page_ui": "修复设置页面 UI 存在的问题。",
        "v085_fixed_title": "修复",
        "v085_non_ascii_launch_paths": "修复游戏本体或创意工坊目录含中文等非 ASCII 字符时无法启动的问题。",
        "v085_game_data_overhauls": "修复游戏数据修改对于 ATC、SFO 等大修 MOD 作用不正常的问题。",
        "v085_steam_friends_utf8": "修复 Steam 好友昵称含特殊字符时程序无法启动的问题。",
        "v082_added_title": "新增",
        "v082_batch_ai_generation": "右键菜单现可为多个已选 MOD 批量使用 AI 生成别名和备注。",
        "v082_search_highlight": "搜索新增高亮模式：保留完整列表、淡化非结果，并跳转到首个结果。",
        "v082_fixed_title": "修复",
        "v082_ai_highlight_cache": "修复切换高亮搜索模式后 AI 生成找不到 MOD 的问题，无需重新扫描即可继续使用。",
        "v081_fixed_title": "修复",
        "v081_friendly_fire": "已在“游戏数据修改”面板恢复“移除友伤”设置。",
        "v081_game_scoped_playsets": "播放集现按游戏分开保存和显示，战锤 3 与三国互不混用。",
        "v081_update_restart": "修复软件更新后自动重启时偶发的错误提示，并避免作者信息刷新异常导致管理器退出。",
        "v081_unit_formation": "修复多倍单位规模下阵型拖拽范围异常，并避免巨炮、战鼓等战争机器重复放大每台机器的牵引坐骑，防止数量错乱和穿模。",
        "v080_added_title": "新增",
        "v080_adjusted_title": "调整",
        "v080_workshop_collection_import": "新增创意工坊 MOD 合集导入：自动订阅缺失 MOD，并按合集原有顺序写入当前播放集。",
        "v080_recruitment_capacity": "游戏数据修改新增单位招募容量调节，可设置 1–5 倍或无限。",
        "v080_editable_shortcuts": "快捷键支持自定义组合键，并会在右键菜单中显示对应快捷键。",
        "v080_themed_controls": "统一下拉框主题样式，并放大设置页标签与更新日志文字。",
        "v080_update_channel": "移除设置中的“软件更新通道”选项，更新检查统一使用内置来源。",
        "v080_fixed_title": "修复",
        "v080_recycle_button": "修复“移入回收站”按钮样式显示不正确的问题。",
        "v080_unicode_paths": "修复了由中文路径导致的各种功能失效。",
        "v070_added_title": "新增",
        "v070_fixed_title": "修复",
        "v065_added_title": "新增",
        "v065_adjusted_title": "调整",
        "v065_fixed_title": "修复",
        "v060_added_title": "新增",
        "v060_adjusted_title": "调整",
        "v060_fixed_title": "修复",
        "v050_added_title": "新增",
        "v050_adjusted_title": "调整",
        "v050_fixed_title": "修复",
        "v030_added_title": "新增",
        "v030_fixed_title": "修复",
        "v020_added_title": "新增",
        "v020_fixed_title": "修复",
        "v010_added_title": "新增",
        "v080_games_title": "游戏支持",
        "v080_three_kingdoms": "新增《全面战争：三国》选择与路径检测；切换游戏后会保留各自目录。",
        "v080_workshop_title": "创意工坊发布",
        "v080_workshop_ownership": "更新按钮只会对当前账号拥有的工坊项目显示；已订阅但不在 Data 中的自有 MOD 也可更新。",
        "v080_publish_simplified": "发布窗口不再选择封面或确认所有权，自动使用与 Pack 同名 PNG 封面。",
        "v080_startup_title": "启动提示",
        "v080_startup_guidance": "启动前会检查必要运行组件，缺失时提供官方下载指引，减少空白窗口。",
        "v080_shortcuts_title": "快捷键",
        "v080_shortcuts": "新增快捷键设置：Shift+W 打开工坊，Shift+R 用 RPFM 打开，Shift+E 切换启用状态，Shift+Enter 启动游戏。",
        "v070_single_entity_unit_rule": "新增单体单位调整规则设置，可在血量与规模之间切换；血量模式仅放大血量而不放大规模。",
        "v070_low_consumption_stability": "修复低消耗模式切换时偶发异常的问题。",
        "v070_game_data_title": "游戏数据修改",
        "v070_unit_scale_ticks": "修复单位规模倍率滑条刻度与实际倍率不一致的问题。",
        "v070_game_data_patch_reliability": "修复部分 MOD 的单位规模或领主与英雄血量未按倍率生效的问题。",
        "v070_workshop_publish_title": "功能修复与调整",
        "v070_workshop_cover": "发布 MOD 时会将同名 PNG 封面与 Pack 一同上传，封面最大 1 MB。",
        "v070_save_mods": "修复“启用存档中的 MOD”无法读取当前存档 MOD 列表的问题。",
        "v070_spanish_language": "新增西班牙语支持。",
        "v065_game_data_title": "游戏数据修改",
        "v065_auto_patch": "启动游戏时会自动校验游戏数据补丁；设置、播放集、启用的 MOD 或游戏数据变化后会自动重新生成。",
        "v065_unit_scale": "单位规模倍率现为 1–5 倍整数滑条，并可选择同步调整领主与英雄血量。",
        "v065_game_data_window": "游戏数据修改窗口现在打开更快。",
        "v065_workshop_title": "创意工坊体验",
        "v065_author_names": "提高作者昵称获取成功率；临时获取失败时会保留已有昵称。",
        "v065_workshop_links": "MOD 右键菜单新增浏览器与 Steam 客户端两个创意工坊跳转入口。",
        "v065_startup_title": "游戏启动",
        "v065_skip_intro": "修复“跳过开场动画”未完整生效的问题。",
        "v060_runtime_title": "启动与低消耗模式",
        "v060_low_consumption": "新增低消耗模式：游戏运行时自动降低管理器资源占用，退出游戏后恢复。",
        "v060_startup_speed": "优化启动和工坊刷新；重复启动会唤醒已有窗口，游戏运行状态识别也更准确。",
        "v060_live_detection": "新增即时 MOD 增删检测：安装或删除 MOD 后自动刷新列表。",
        "v060_game_data_title": "游戏数据修改",
        "v060_game_data_controls": "新增“游戏数据修改”窗口，可调整兵模人数和友伤选项；支持一键生成补丁，保存更改时也会自动更新。",
        "v060_unit_multiplier": "订阅 Dynamic Unit Size 后，可按 0.5–5 倍调整普通单位、骑乘与战争机器的兵模人数。",
        "v060_friendly_fire": "订阅 Dynamic No Friendly Fire 后，可分别禁用单位友伤和法术友伤，增益与治疗仍可正常作用于友军。",
        "v060_library_title": "存档与 MOD 列表操作",
        "v060_save_actions": "存档列表可一键启用存档使用的 MOD，并与当前启用列表进行比较。",
        "v060_select_all": "新增 Ctrl+A 全选和双击启用或停用，让 MOD 列表操作更快捷。",
        "v060_official_profiles": "支持导入官方 MOD 启动器配置，快速新建播放集或替换当前播放集。",
        "v060_dependency_refresh": "修复工坊依赖刷新不准确的问题，让缺失依赖警告更可靠。",
        "v060_files_title": "MOD 文件与工坊操作",
        "v060_copy_path": "支持批量复制 MOD 路径，详情栏的 MOD 名称和文件名也可直接选中复制。",
        "v060_safe_delete": "支持将 MOD 文件移入 Windows 回收站，误删后仍可恢复。",
        "v060_unsubscribe_cleanup": "取消订阅时会同步清理对应工坊文件，并立即刷新 MOD 列表。",
        "v060_force_update_wait": "强制更新现在可重新下载并恢复缺失的工坊 MOD 文件。",
        "v050_settings_title": "设置与关于项目",
        "v050_settings_pages": "设置界面拆分为基础设置、功能（游戏启动增强）、AI 集成和关于项目四个分页。",
        "v050_about_page": "新增关于项目页，集中显示版本与更新信息；下载入口仅指向 GitHub、Gitee 发布页，反馈与交流提供 GitHub Issues 和 QQ 群 592799189。",
        "v050_startup_title": "启动恢复与列表操作",
        "v050_restore_last_order": "首次启动时自动读取 Warhammer III 上次使用的 used_mods.txt，仅按本机已安装 MOD 恢复启用状态与加载顺序，不会下载或订阅缺失 MOD。",
        "v050_drag_lists": "已启用与未启用 MOD 均支持单项或 Ctrl、Shift 批量拖拽；可在两栏之间移动，已启用顺序即时保存，未启用顺序仅在本次运行中保留。",
        "v050_button_style": "统一打开目录、重新扫描、刷新工坊信息和打开游戏目录等按钮样式，并将页面入口统一命名为“创意工坊页面”。",
        "v050_workshop_title": "创意工坊发布与分享码导入",
        "v050_publish_language": "发布 MOD 更新时可选择语言，默认使用当前界面语言；切换语言后自动载入对应的创意工坊标题与描述，只有英文简介时自动使用英文。",
        "v050_change_note": "将“更新说明”调整为默认为空的“更新日志”，并通过本地 Steamworks 补丁写入所选发布语言。",
        "v050_share_subscribe": "分享码导入会列出未订阅的 MOD，在用户确认后自动订阅，并在下载完成、重新扫描后还原到播放集。",
        "v050_language_title": "内置多语言",
        "v050_system_language": "首次启动时根据系统语言自动选择简体中文、英语、韩语、俄语或日语；检测失败或系统语言不受支持时默认使用英语。",
        "v050_builtin_languages": "界面与更新日志现已内置简体中文、英语、韩语、俄语和日语。",
        "v050_single_language_ui": "统一各语言下的按钮、标题、状态与提示文本，避免界面混用其他语言。",
        "v050_warning_title": "警告检测与提示修复",
        "v050_outdated_check": "修复过期 MOD 检查的时间比较方向错误；现在仅当 MOD 在游戏本体更新后尚未更新时提示，同步更新说明文本，并兼容旧版忽略记录。",
        "v050_enabled_dependency_scope": "缺失依赖警告现在只检查已启用 MOD；启用、停用、排序、跨栏拖放、切换播放集或导入后都会立即重新检测。",
        "v050_dependency_cache_warning": "当 Steam 暂时无法读取部分创意工坊依赖时，明确说明正在使用缓存且缺失依赖结果可能不是最新状态，并允许在本次运行中忽略该提示。",
        "v050_docs_title": "文档与项目说明",
        "v050_readme": "重写 README 的用户功能介绍，精简不必要的实现细节，并补充 Warhammer Mod Manager 与 RimCrow 的致谢。",
        "v030_title": "问题管理与文件定位",
        "v030_data_location": "修复 Data 目录中的 MOD 无法在资源管理器中准确定位 Pack 文件的问题。",
        "v030_ignore_issues": "右键菜单新增“忽略问题”，支持按 MOD 忽略或恢复过期与缺失依赖警告。",
        "v030_warning_window": "将警告入口移到“已启用 MOD”标题栏中央，并新增可逐条忽略问题的居中窗口。",
        "v020_title": "更新与批量操作",
        "v020_dual_source": "支持按当前语言优先检查 Gitee 或 GitHub，并在双源间自动回退。",
        "v020_context_menu": "右键菜单新增“打开文件目录”；批量选择时显示操作数量，并禁用 RPFM 单项操作。",
        "v020_pyinstaller": "修复产品名称含撇号时 PyInstaller 一键打包失败的问题。",
        "v010_title": "管理器基础功能",
        "v010_playsets": "使用播放集管理 MOD 启用状态与加载顺序，所有修改即时保存。",
        "v010_game_workshop": "支持继续游戏、从存档列表载入、Workshop 管理与依赖缺失警告。",
        "v010_updates": "支持自动检查新版本、下载校验、安全替换以及应用内更新日志。",
    },
    "en-US": {
        "v088_added_title": "Added",
        "v088_dependency_action": "The missing-dependency warning can now subscribe to and enable missing dependencies directly.",
        "v088_adjusted_title": "Adjusted",
        "v088_unit_formation_width": "Unit scale multipliers now also allow formations to be dragged wider.",
        "v087_added_title": "Added",
        "v087_type_order": "Type management now supports reordering built-in and custom types, with the order persisted.",
        "v087_type_sort": "Added type-based MOD sorting that follows the configured type order.",
        "v087_manual_type": "Added Manual input to the type context menu with Shift+F for applying a type to selected MODs.",
        "v087_adjusted_title": "Adjusted",
        "v087_readability": "Enlarged text in MOD details, bottom actions, type management, and Settings for better readability.",
        "v087_fixed_title": "Fixed",
        "v087_publish_modal_ui": "Fixed inconsistent styling for the close button and textarea resize control in the Workshop publish/update window.",
        "v086_fixed_title": "Fixed",
        "v086_playset_dependencies": "Fixed missing-dependency warnings when a required MOD is installed but not enabled in the current playset.",
        "v086_settings_page_ui": "Fixed UI issues on the Settings page.",
        "v085_fixed_title": "Fixed",
        "v085_non_ascii_launch_paths": "Fixed game launch when the game installation or Workshop directory contains Chinese or other non-ASCII characters.",
        "v085_game_data_overhauls": "Fixed Game Data Modification behaving incorrectly with overhaul MODs such as ATC and SFO.",
        "v085_steam_friends_utf8": "Fixed startup failing when a Steam friend name contains special characters.",
        "v082_added_title": "Added",
        "v082_batch_ai_generation": "The context menu can now use AI to generate aliases and notes for multiple selected MODs.",
        "v082_search_highlight": "Search now offers a highlight mode that keeps the full list visible, dims nonmatches, and jumps to the first result.",
        "v082_fixed_title": "Fixes",
        "v082_ai_highlight_cache": "Fixed AI generation reporting that a MOD was missing after switching highlight search mode; rescanning is no longer required.",
        "v081_fixed_title": "Fixes",
        "v081_friendly_fire": "Restored the Remove Friendly Fire setting in Game Data Modification.",
        "v081_game_scoped_playsets": "Playsets are now stored and shown separately for each game, so WARHAMMER III and THREE KINGDOMS no longer mix.",
        "v081_update_restart": "Fixed an occasional error after update restart and prevented author refresh failures from exiting the manager.",
        "v081_unit_formation": "Fixed formation dragging at increased unit scales and stopped cannons, war drums, and other engines from multiplying their per-engine draught mounts.",
        "v080_added_title": "Added",
        "v080_adjusted_title": "Adjusted",
        "v080_workshop_collection_import": "Added Workshop collection import: missing MODs are subscribed automatically and the current playset follows the collection order.",
        "v080_recruitment_capacity": "Added recruitment-capacity controls to game-data modification, with 1–5× and Unlimited options.",
        "v080_editable_shortcuts": "Keyboard shortcuts now support custom key combinations and are shown in the context menu.",
        "v080_themed_controls": "Unified dropdown styling and enlarged the settings tabs and changelog text for readability.",
        "v080_update_channel": "Removed the custom software update channel; update checks now use the built-in sources.",
        "v080_fixed_title": "Fixed",
        "v080_recycle_button": "Fixed the incorrect styling of the Move to Recycle Bin button.",
        "v080_unicode_paths": "Fixed various features failing when the application is placed in a path containing Chinese characters.",
        "v070_added_title": "Added",
        "v070_fixed_title": "Fixed",
        "v065_added_title": "Added",
        "v065_adjusted_title": "Adjusted",
        "v065_fixed_title": "Fixed",
        "v060_added_title": "Added",
        "v060_adjusted_title": "Adjusted",
        "v060_fixed_title": "Fixed",
        "v050_added_title": "Added",
        "v050_adjusted_title": "Adjusted",
        "v050_fixed_title": "Fixed",
        "v030_added_title": "Added",
        "v030_fixed_title": "Fixed",
        "v020_added_title": "Added",
        "v020_fixed_title": "Fixed",
        "v010_added_title": "Added",
        "v080_games_title": "Game support",
        "v080_three_kingdoms": "Added Total War: THREE KINGDOMS selection and path detection; each game's folders remain saved when switching.",
        "v080_workshop_title": "Workshop publishing",
        "v080_workshop_ownership": "Updates are shown only for Workshop projects owned by the current account; subscribed owner MODs can update even outside Data.",
        "v080_publish_simplified": "Publishing no longer asks for a cover or ownership confirmation and automatically uses the same-name PNG cover.",
        "v080_startup_title": "Startup guidance",
        "v080_startup_guidance": "Checks required runtime components before startup and offers official download guidance when one is missing, reducing blank windows.",
        "v080_shortcuts_title": "Keyboard shortcuts",
        "v080_shortcuts": "Added keyboard shortcuts: Shift+W opens Workshop, Shift+R opens RPFM, Shift+E toggles enabled state, and Shift+Enter launches the game.",
        "v070_single_entity_unit_rule": "Added a single-entity unit adjustment setting that switches between health and scale; Health mode increases health without increasing unit scale.",
        "v070_low_consumption_stability": "Fixed an intermittent error when switching low-consumption mode.",
        "v070_game_data_title": "Game data modification",
        "v070_unit_scale_ticks": "Fixed unit scale slider tick marks not matching the selected scale.",
        "v070_game_data_patch_reliability": "Fixed game-data scaling not applying to some MOD units or lord and hero health.",
        "v070_workshop_publish_title": "Feature fixes and adjustments",
        "v070_workshop_cover": "Publishing a MOD now uploads its same-name PNG cover with the Pack; covers are limited to 1 MB.",
        "v070_save_mods": "Fixed Enable MODs Used in Save failing to read MODs from current saves.",
        "v070_spanish_language": "Added Spanish support.",
        "v065_game_data_title": "Game data modification",
        "v065_auto_patch": "The game-data patch is checked automatically when the game launches and regenerated after relevant settings, playsets, enabled MODs, or game data change.",
        "v065_unit_scale": "Unit scale now uses an integer 1–5 slider, with an option to scale lord and hero health.",
        "v065_game_data_window": "Game Data Modification now opens faster.",
        "v065_workshop_title": "Workshop experience",
        "v065_author_names": "Workshop author names are more reliable, while existing names remain available when a refresh temporarily fails.",
        "v065_workshop_links": "MOD context menus now provide separate Workshop links for the browser and Steam client.",
        "v065_startup_title": "Game launch",
        "v065_skip_intro": "Fixed Skip Intro so all opening movies are skipped as expected.",
        "v060_runtime_title": "Startup and low-consumption mode",
        "v060_low_consumption": "Added low-consumption mode to reduce manager resource usage while the game is running and restore it after the game closes.",
        "v060_startup_speed": "Improved startup and Workshop refresh; reopening WMM activates the existing window, with more accurate game-status detection.",
        "v060_live_detection": "Added live MOD change detection so the list refreshes automatically after MODs are installed or removed.",
        "v060_game_data_title": "Game data modification",
        "v060_game_data_controls": "Added a Game Data Modification window for model counts and friendly fire; generate the patch with one click, with automatic updates when changes are saved.",
        "v060_unit_multiplier": "Subscribe to Dynamic Unit Size to scale model counts for regular units, mounts, and war machines from 0.5× to 5×.",
        "v060_friendly_fire": "Subscribe to Dynamic No Friendly Fire to disable unit and spell friendly fire separately while keeping buffs and healing available to allies.",
        "v060_library_title": "Saves and MOD list controls",
        "v060_save_actions": "Save entries can now enable their MODs with one click and compare them with the currently enabled list.",
        "v060_select_all": "Added Ctrl+A selection and double-click enable or disable for faster MOD list control.",
        "v060_official_profiles": "Official MOD launcher profiles can now create a new playset or replace the current one.",
        "v060_dependency_refresh": "Fixed inaccurate Workshop dependency refreshes so missing-dependency warnings are more reliable.",
        "v060_files_title": "MOD files and Workshop actions",
        "v060_copy_path": "MOD paths can now be copied in batches, and MOD names and filenames in the details panel can be selected and copied.",
        "v060_safe_delete": "MOD files can now be moved to the Windows Recycle Bin so accidental deletions remain recoverable.",
        "v060_unsubscribe_cleanup": "Unsubscribing now removes the matching Workshop files and refreshes the MOD list immediately.",
        "v060_force_update_wait": "Force Update can now redownload and restore missing Workshop MOD files.",
        "v050_settings_title": "Settings and About",
        "v050_settings_pages": "Settings are divided into Basic, Features (game launch enhancements), AI Integration, and About pages.",
        "v050_about_page": "Added an About page with version and update information. Downloads link only to the GitHub and Gitee release pages, while feedback and discussion use GitHub Issues and QQ group 592799189.",
        "v050_startup_title": "Startup recovery and list controls",
        "v050_restore_last_order": "On first launch, the manager reads Warhammer III's last used_mods.txt and restores enabled state and load order for locally installed MODs only; missing MODs are never downloaded or subscribed automatically.",
        "v050_drag_lists": "Enabled and inactive MODs support single, Ctrl, and Shift batch dragging. MODs can move between lists; enabled order saves instantly, while inactive order lasts for the current session only.",
        "v050_button_style": "Unified the styles of directory, rescan, Workshop refresh, and game-directory actions, and consistently named the page entry Workshop Page.",
        "v050_workshop_title": "Workshop publishing and share-code import",
        "v050_publish_language": "Choose a language when publishing a MOD update, defaulting to the current interface language. Changing language loads the corresponding Workshop title and description, with automatic English fallback when only English content exists.",
        "v050_change_note": "Renamed Update Notes to an initially empty Update Log and added the selected publishing language through the local Steamworks patch.",
        "v050_share_subscribe": "Share-code import lists unsubscribed MODs, subscribes after confirmation, and restores them to the playset after download and rescan.",
        "v050_language_title": "Built-in languages",
        "v050_system_language": "On first launch, the interface follows the system language when it is Simplified Chinese, English, Korean, Russian, or Japanese; detection failures and unsupported languages default to English.",
        "v050_builtin_languages": "The interface and changelog now include Simplified Chinese, English, Korean, Russian, and Japanese.",
        "v050_single_language_ui": "Unified buttons, headings, status text, and prompts so the selected interface language is not mixed with other languages.",
        "v050_warning_title": "Warning detection and messaging fixes",
        "v050_outdated_check": "Fixed the reversed timestamp comparison in outdated-MOD detection. A warning now appears only when a MOD has not been updated since the game update; the help text was clarified and previous ignore records remain compatible.",
        "v050_enabled_dependency_scope": "Missing-dependency warnings now apply only to enabled MODs and are recomputed immediately after enabling, disabling, reordering, cross-list dragging, switching playsets, or importing.",
        "v050_dependency_cache_warning": "When Steam temporarily cannot read some Workshop dependencies, the manager now explains that cached data is in use and missing-dependency results may be stale, and the notice can be ignored for the current session.",
        "v050_docs_title": "Documentation and project information",
        "v050_readme": "Reworked the README around user-facing features, removed unnecessary implementation detail, and added acknowledgements for Warhammer Mod Manager and RimCrow.",
        "v030_title": "Issue management and file location",
        "v030_data_location": "Fixed locating Pack files for MODs stored in Data from File Explorer.",
        "v030_ignore_issues": "Added Ignore Issue to the context menu, allowing outdated and missing-dependency warnings to be ignored or restored per MOD.",
        "v030_warning_window": "Moved the warning entry to the center of the Enabled MODs heading and added a centered window for ignoring individual issues.",
        "v020_title": "Updates and batch actions",
        "v020_dual_source": "Added language-aware update priority between Gitee and GitHub with automatic fallback.",
        "v020_context_menu": "Added Open File Location to the context menu; batch selections show their item count and disable the single-item RPFM action.",
        "v020_pyinstaller": "Fixed one-click PyInstaller packaging when the product name contains an apostrophe.",
        "v010_title": "Core manager features",
        "v010_playsets": "Manage enabled MODs and load order with playsets; every change is saved immediately.",
        "v010_game_workshop": "Supports continuing games, loading from the save list, Workshop management, and missing-dependency warnings.",
        "v010_updates": "Supports automatic update checks, verified downloads, safe replacement, and an in-app changelog.",
    },
    "ko-KR": {
        "v088_added_title": "추가",
        "v088_dependency_action": "누락된 종속성 경고 화면에서 누락된 종속성을 바로 구독하고 활성화할 수 있습니다.",
        "v088_adjusted_title": "조정",
        "v088_unit_formation_width": "유닛 규모 배율을 조정하면 이제 진형을 더 넓게 드래그할 수 있습니다.",
        "v087_added_title": "추가",
        "v087_type_order": "내장 유형과 사용자 지정 유형의 순서를 조정하고 저장할 수 있습니다.",
        "v087_type_sort": "설정된 유형 순서를 따르는 유형별 MOD 정렬을 추가했습니다.",
        "v087_manual_type": "유형 컨텍스트 메뉴에 선택한 MOD에 유형을 적용하는 수동 입력과 Shift+F 단축키를 추가했습니다.",
        "v087_adjusted_title": "조정",
        "v087_readability": "MOD 세부 정보, 하단 작업 버튼, 유형 관리 및 설정 페이지의 글자를 키워 가독성을 높였습니다.",
        "v087_fixed_title": "수정",
        "v087_publish_modal_ui": "창작마당 게시/업데이트 창의 닫기 버튼과 텍스트 영역 크기 조절 컨트롤 스타일이 일치하지 않던 문제를 수정했습니다.",
        "v086_fixed_title": "수정",
        "v086_playset_dependencies": "필수 MOD가 설치되어 있지만 현재 플레이세트에서 활성화되지 않은 경우 누락된 종속성 경고가 표시되지 않던 문제를 수정했습니다.",
        "v086_settings_page_ui": "설정 페이지의 UI 문제를 수정했습니다.",
        "v085_fixed_title": "수정",
        "v085_non_ascii_launch_paths": "게임 설치 또는 창작마당 경로에 중국어 등 ASCII 이외 문자가 있으면 실행되지 않던 문제를 수정했습니다.",
        "v085_game_data_overhauls": "ATC, SFO 등 대형 개편 MOD에서 게임 데이터 수정이 정상적으로 적용되지 않던 문제를 수정했습니다.",
        "v085_steam_friends_utf8": "Steam 친구 이름에 특수 문자가 있으면 프로그램이 시작되지 않던 문제를 수정했습니다.",
        "v082_added_title": "추가",
        "v082_batch_ai_generation": "이제 우클릭 메뉴에서 여러 선택한 MOD의 별칭과 메모를 AI로 일괄 생성할 수 있습니다.",
        "v082_search_highlight": "검색 결과 강조 모드가 추가되어 전체 목록을 유지하고 비일치 항목을 흐리게 하며 첫 결과로 이동합니다.",
        "v082_fixed_title": "수정",
        "v082_ai_highlight_cache": "검색 결과 강조 모드 전환 후 AI 생성에서 MOD를 찾지 못하던 문제를 수정해 다시 스캔하지 않아도 사용할 수 있습니다.",
        "v081_fixed_title": "수정",
        "v081_friendly_fire": "게임 데이터 수정 화면에 아군 오사 제거 설정을 복원했습니다.",
        "v081_game_scoped_playsets": "플레이세트를 게임별로 따로 저장하고 표시하여 WARHAMMER III와 THREE KINGDOMS가 섞이지 않습니다.",
        "v081_update_restart": "업데이트 후 자동 재시작 오류를 수정하고 작성자 정보 새로 고침 실패로 관리자가 종료되지 않도록 했습니다.",
        "v081_unit_formation": "다중 유닛 규모의 대형 조절을 수정하고, 대포와 전쟁 북 같은 전쟁 기계가 각 기계의 견인 탈것 수를 중복 확대하지 않도록 했습니다.",
        "v080_added_title": "추가",
        "v080_adjusted_title": "조정",
        "v080_workshop_collection_import": "창작마당 컬렉션 가져오기를 추가했습니다. 누락된 MOD를 자동 구독하고 현재 플레이 세트를 컬렉션 순서로 구성합니다.",
        "v080_recruitment_capacity": "게임 데이터 수정에 모집 한도 조정을 추가했습니다. 1–5배 또는 무제한을 선택할 수 있습니다.",
        "v080_editable_shortcuts": "키보드 단축키에서 사용자 지정 키 조합을 지원하며, 컨텍스트 메뉴에도 표시합니다.",
        "v080_themed_controls": "드롭다운 테마를 통일하고 설정 탭과 변경 내역 글자를 키워 가독성을 높였습니다.",
        "v080_update_channel": "설정에서 소프트웨어 업데이트 채널을 제거했으며 업데이트 확인은 내장 소스를 사용합니다.",
        "v080_fixed_title": "수정",
        "v080_recycle_button": "‘휴지통으로 이동’ 버튼 스타일이 잘못 표시되던 문제를 수정했습니다.",
        "v080_unicode_paths": "프로그램이 중국어 문자가 포함된 경로에 있을 때 여러 기능이 작동하지 않던 문제를 수정했습니다.",
        "v070_added_title": "추가",
        "v070_fixed_title": "수정",
        "v065_added_title": "추가",
        "v065_adjusted_title": "조정",
        "v065_fixed_title": "수정",
        "v060_added_title": "추가",
        "v060_adjusted_title": "조정",
        "v060_fixed_title": "수정",
        "v050_added_title": "추가",
        "v050_adjusted_title": "조정",
        "v050_fixed_title": "수정",
        "v030_added_title": "추가",
        "v030_fixed_title": "수정",
        "v020_added_title": "추가",
        "v020_fixed_title": "수정",
        "v010_added_title": "추가",
        "v080_games_title": "게임 지원",
        "v080_three_kingdoms": "토탈 워: 삼국 선택과 경로 감지를 추가했으며, 게임을 전환해도 각 게임의 폴더를 유지합니다.",
        "v080_workshop_title": "창작마당 게시",
        "v080_workshop_ownership": "현재 계정이 소유한 창작마당 항목에만 업데이트 버튼을 표시하며, Data 밖에 있는 구독한 본인 MOD도 업데이트할 수 있습니다.",
        "v080_publish_simplified": "게시 창에서 표지 선택과 소유 확인을 제거하고 Pack과 같은 이름의 PNG 표지를 자동으로 사용합니다.",
        "v080_startup_title": "시작 안내",
        "v080_startup_guidance": "시작 전에 필요한 실행 구성 요소를 확인하고, 없으면 공식 다운로드 안내를 표시해 빈 창을 줄입니다.",
        "v080_shortcuts_title": "키보드 단축키",
        "v080_shortcuts": "단축키 설정을 추가했습니다. Shift+W는 창작마당을 열고, Shift+R은 RPFM으로 열며, Shift+E는 활성 상태를 전환하고, Shift+Enter는 게임을 실행합니다.",
        "v070_single_entity_unit_rule": "단일 개체 유닛 조정 설정을 추가했습니다. 체력과 규모 중에서 선택할 수 있으며, 체력 모드에서는 체력만 늘어나고 규모는 늘어나지 않습니다.",
        "v070_low_consumption_stability": "저소비 모드를 전환할 때 간헐적으로 발생하던 오류를 수정했습니다.",
        "v070_game_data_title": "게임 데이터 수정",
        "v070_unit_scale_ticks": "유닛 규모 배율 슬라이더 눈금이 선택한 배율과 일치하지 않던 문제를 수정했습니다.",
        "v070_game_data_patch_reliability": "일부 MOD에서 유닛 규모 또는 군주와 영웅 체력이 배율대로 적용되지 않던 문제를 수정했습니다.",
        "v070_workshop_publish_title": "기능 수정 및 조정",
        "v070_workshop_cover": "MOD 게시 시 같은 이름의 PNG 표지를 Pack과 함께 업로드하며, 표지는 최대 1MB까지 지원합니다.",
        "v070_save_mods": "‘저장에 사용된 MOD 활성화’가 현재 저장 파일의 MOD 목록을 읽지 못하던 문제를 수정했습니다.",
        "v070_spanish_language": "스페인어 지원을 추가했습니다.",
        "v065_game_data_title": "게임 데이터 수정",
        "v065_auto_patch": "게임을 실행할 때 게임 데이터 패치를 자동으로 확인하며, 관련 설정, 플레이 세트, 활성 MOD 또는 게임 데이터가 바뀌면 자동으로 다시 생성합니다.",
        "v065_unit_scale": "유닛 규모 배율을 1–5 정수 슬라이더로 변경하고 군주와 영웅의 체력도 함께 조정할 수 있습니다.",
        "v065_game_data_window": "게임 데이터 수정 창이 더 빠르게 열립니다.",
        "v065_workshop_title": "창작마당 사용성",
        "v065_author_names": "창작마당 작성자 이름을 더 안정적으로 표시하며, 일시적으로 가져오지 못해도 기존 이름을 유지합니다.",
        "v065_workshop_links": "MOD 우클릭 메뉴에서 브라우저와 Steam 클라이언트용 창작마당 링크를 각각 열 수 있습니다.",
        "v065_startup_title": "게임 시작",
        "v065_skip_intro": "‘오프닝 영상 건너뛰기’가 모든 시작 영상을 정상적으로 건너뛰도록 수정했습니다.",
        "v060_runtime_title": "시작 및 저소비 모드",
        "v060_low_consumption": "게임 실행 중 관리자의 리소스 사용량을 줄이고 게임 종료 후 자동 복원하는 저소비 모드를 추가했습니다.",
        "v060_startup_speed": "시작과 창작마당 새로 고침을 개선했으며, WMM을 다시 실행하면 기존 창이 열리고 게임 실행 상태도 더 정확하게 감지합니다.",
        "v060_live_detection": "MOD 설치 또는 삭제 후 목록을 자동으로 새로 고치는 실시간 MOD 변경 감지를 추가했습니다.",
        "v060_game_data_title": "게임 데이터 수정",
        "v060_game_data_controls": "유닛 모델 수와 아군 피해 옵션을 조정하고 패치를 생성할 수 있으며, 변경 사항을 저장하면 자동으로 업데이트됩니다.",
        "v060_unit_multiplier": "Dynamic Unit Size를 구독하면 일반 유닛, 탑승물, 전쟁 기계의 모델 수를 0.5~5배로 조정할 수 있습니다.",
        "v060_friendly_fire": "Dynamic No Friendly Fire를 구독하면 유닛과 주문의 아군 피해를 각각 끌 수 있으며 강화와 치유는 아군에게 계속 적용됩니다.",
        "v060_library_title": "저장 파일 및 MOD 목록 조작",
        "v060_save_actions": "저장 파일에서 사용한 MOD를 한 번에 활성화하고 현재 활성 목록과 비교할 수 있습니다.",
        "v060_select_all": "Ctrl+A 전체 선택과 더블 클릭 활성화·비활성화를 추가해 MOD 목록을 더 빠르게 조작할 수 있습니다.",
        "v060_official_profiles": "공식 MOD 런처 프로필을 가져와 새 플레이 세트를 만들거나 현재 플레이 세트를 바꿀 수 있습니다.",
        "v060_dependency_refresh": "창작마당 종속성 새로 고침 오류를 수정해 누락 종속성 경고가 더 정확해졌습니다.",
        "v060_files_title": "MOD 파일 및 창작마당 작업",
        "v060_copy_path": "여러 MOD 경로를 한 번에 복사할 수 있으며 상세 패널의 MOD 이름과 파일 이름도 선택해 복사할 수 있습니다.",
        "v060_safe_delete": "MOD 파일을 Windows 휴지통으로 이동해 실수로 삭제해도 복구할 수 있습니다.",
        "v060_unsubscribe_cleanup": "구독을 취소하면 해당 창작마당 파일을 함께 정리하고 MOD 목록을 즉시 새로 고칩니다.",
        "v060_force_update_wait": "강제 업데이트로 누락된 창작마당 MOD 파일을 다시 다운로드하고 복원할 수 있습니다.",
        "v050_settings_title": "설정 및 프로젝트 정보",
        "v050_settings_pages": "설정을 기본 설정, 기능(게임 실행 향상), AI 통합 및 프로젝트 정보의 네 페이지로 나눴습니다.",
        "v050_about_page": "버전과 업데이트 정보를 한곳에 제공하는 프로젝트 정보 페이지를 추가했습니다. 다운로드는 GitHub와 Gitee 릴리스 페이지만 연결하며, 피드백과 소통은 GitHub Issues와 QQ 그룹 592799189를 이용합니다.",
        "v050_startup_title": "시작 복원 및 목록 조작",
        "v050_restore_last_order": "처음 실행할 때 Warhammer III의 마지막 used_mods.txt를 읽고 로컬에 설치된 MOD의 활성 상태와 로드 순서만 복원합니다. 누락된 MOD를 다운로드하거나 구독하지 않습니다.",
        "v050_drag_lists": "활성 및 비활성 MOD 목록 모두 단일, Ctrl, Shift 일괄 드래그를 지원합니다. 목록 사이로 이동할 수 있으며 활성 순서는 즉시 저장되고 비활성 순서는 현재 실행 중에만 유지됩니다.",
        "v050_button_style": "폴더 열기, 다시 검색, 창작마당 정보 새로 고침, 게임 폴더 열기 등의 버튼 스타일을 통일하고 페이지 항목 이름을 창작마당 페이지로 통일했습니다.",
        "v050_workshop_title": "창작마당 게시 및 공유 코드 가져오기",
        "v050_publish_language": "MOD 업데이트 게시 언어를 선택할 수 있으며 기본값은 현재 인터페이스 언어입니다. 언어를 바꾸면 해당 창작마당 제목과 설명을 불러오며 영어 내용만 있으면 영어를 자동 사용합니다.",
        "v050_change_note": "업데이트 설명을 기본적으로 비어 있는 업데이트 로그로 바꾸고 로컬 Steamworks 패치를 통해 선택한 게시 언어를 기록합니다.",
        "v050_share_subscribe": "공유 코드 가져오기에서 미구독 MOD를 표시하고 확인 후 자동 구독하며 다운로드와 재검색 후 플레이 세트에 복원합니다.",
        "v050_language_title": "내장 다국어",
        "v050_system_language": "처음 실행할 때 시스템 언어가 중국어 간체, 영어, 한국어, 러시아어 또는 일본어이면 자동으로 적용하며, 감지에 실패하거나 지원하지 않는 언어이면 영어를 기본값으로 사용합니다.",
        "v050_builtin_languages": "인터페이스와 변경 내역에 중국어 간체, 영어, 한국어, 러시아어 및 일본어를 내장했습니다.",
        "v050_single_language_ui": "선택한 인터페이스 언어에 다른 언어가 섞이지 않도록 버튼, 제목, 상태 및 알림 문구를 통일했습니다.",
        "v050_warning_title": "경고 감지 및 안내 수정",
        "v050_outdated_check": "오래된 MOD 검사에서 시간 비교 방향이 반대로 적용되던 문제를 수정했습니다. 이제 게임 업데이트 후 MOD가 갱신되지 않은 경우에만 경고하며, 도움말을 명확히 하고 이전 무시 기록도 계속 호환합니다.",
        "v050_enabled_dependency_scope": "누락 종속성 경고는 이제 활성 MOD만 검사하며, 활성화, 비활성화, 순서 변경, 목록 간 드래그, 플레이 세트 전환 또는 가져오기 후 즉시 다시 검사합니다.",
        "v050_dependency_cache_warning": "Steam에서 일부 창작마당 종속성을 일시적으로 읽지 못하면 캐시 사용 중이며 누락 종속성 결과가 최신이 아닐 수 있음을 명확히 안내하고, 현재 실행 중에는 해당 알림을 무시할 수 있습니다.",
        "v050_docs_title": "문서 및 프로젝트 정보",
        "v050_readme": "README를 사용자 기능 중심으로 다시 정리하고 불필요한 구현 세부 정보를 줄였으며 Warhammer Mod Manager와 RimCrow에 대한 감사를 추가했습니다.",
        "v030_title": "문제 관리 및 파일 위치",
        "v030_data_location": "Data 폴더의 MOD Pack 파일을 파일 탐색기에서 정확히 찾지 못하던 문제를 수정했습니다.",
        "v030_ignore_issues": "컨텍스트 메뉴에 문제 무시를 추가하여 MOD별로 오래됨 및 누락된 종속성 경고를 무시하거나 복원할 수 있습니다.",
        "v030_warning_window": "경고 항목을 활성 MOD 제목 중앙으로 옮기고 개별 문제를 무시할 수 있는 중앙 창을 추가했습니다.",
        "v020_title": "업데이트 및 일괄 작업",
        "v020_dual_source": "현재 언어에 따라 Gitee 또는 GitHub를 우선 확인하고 자동 대체하도록 했습니다.",
        "v020_context_menu": "컨텍스트 메뉴에 파일 위치 열기를 추가했습니다. 일괄 선택 시 항목 수를 표시하고 단일 항목 RPFM 작업을 비활성화합니다.",
        "v020_pyinstaller": "제품 이름에 아포스트로피가 있을 때 PyInstaller 원클릭 패키징이 실패하는 문제를 수정했습니다.",
        "v010_title": "관리자 기본 기능",
        "v010_playsets": "플레이 세트로 MOD 활성 상태와 로드 순서를 관리하며 모든 변경을 즉시 저장합니다.",
        "v010_game_workshop": "게임 계속하기, 저장 목록 불러오기, 창작마당 관리 및 누락된 종속성 경고를 지원합니다.",
        "v010_updates": "자동 업데이트 확인, 다운로드 검증, 안전한 교체 및 앱 내 변경 내역을 지원합니다.",
    },
    "ru-RU": {
        "v088_added_title": "Добавлено",
        "v088_dependency_action": "На экране предупреждений о недостающих зависимостях теперь можно сразу подписаться на них и включить их.",
        "v088_adjusted_title": "Изменено",
        "v088_unit_formation_width": "Множитель размера отрядов теперь также позволяет растягивать строй шире.",
        "v087_added_title": "Добавлено",
        "v087_type_order": "Добавлена настройка и сохранение порядка встроенных и пользовательских типов.",
        "v087_type_sort": "Добавлена сортировка MOD по настроенному порядку типов.",
        "v087_manual_type": "В контекстное меню типов добавлен ручной ввод с сочетанием Shift+F для применения типа к выбранным MOD.",
        "v087_adjusted_title": "Изменено",
        "v087_readability": "Увеличен размер текста в сведениях о MOD, нижних кнопках, управлении типами и настройках.",
        "v087_fixed_title": "Исправлено",
        "v087_publish_modal_ui": "Исправлен разный стиль кнопки закрытия и элемента изменения размера текста в окне публикации и обновления Workshop.",
        "v086_fixed_title": "Исправлено",
        "v086_playset_dependencies": "Исправлено отсутствие предупреждения о зависимости, когда требуемый MOD установлен, но не включён в текущем наборе.",
        "v086_settings_page_ui": "Исправлены проблемы интерфейса на странице настроек.",
        "v085_fixed_title": "Исправлено",
        "v085_non_ascii_launch_paths": "Исправлен запуск игры, когда путь к игре или каталогу Мастерской содержит китайские или другие не-ASCII символы.",
        "v085_game_data_overhauls": "Исправлена некорректная работа изменения игровых данных с крупными модами, такими как ATC и SFO.",
        "v085_steam_friends_utf8": "Исправлен сбой запуска, когда имя друга в Steam содержит специальные символы.",
        "v082_added_title": "Добавлено",
        "v082_batch_ai_generation": "В контекстном меню теперь можно с помощью ИИ создать псевдонимы и заметки для нескольких выбранных MOD.",
        "v082_search_highlight": "Поиск получил режим подсветки: полный список остаётся видимым, несовпадения приглушаются, выполняется переход к первому результату.",
        "v082_fixed_title": "Исправления",
        "v082_ai_highlight_cache": "Исправлена ошибка, из-за которой после включения подсветки поиска ИИ не находил MOD; повторное сканирование больше не требуется.",
        "v081_fixed_title": "Исправления",
        "v081_friendly_fire": "В панели изменения игровых данных восстановлена настройка отключения дружественного огня.",
        "v081_game_scoped_playsets": "Наборы модов теперь сохраняются и отображаются отдельно для каждой игры: WARHAMMER III и THREE KINGDOMS не смешиваются.",
        "v081_update_restart": "Исправлена ошибка автоперезапуска после обновления; сбой обновления данных авторов больше не закрывает менеджер.",
        "v081_unit_formation": "Исправлено растягивание строя; пушки, боевые барабаны и другие машины больше не умножают повторно число тягловых животных на каждую машину.",
        "v080_added_title": "Добавлено",
        "v080_adjusted_title": "Изменено",
        "v080_workshop_collection_import": "Добавлен импорт коллекций Мастерской: недостающие MOD подписываются автоматически, а текущий набор получает порядок коллекции.",
        "v080_recruitment_capacity": "В изменение игровых данных добавлена настройка лимита найма: 1–5× или без ограничений.",
        "v080_editable_shortcuts": "Горячие клавиши поддерживают пользовательские сочетания и отображаются в контекстном меню.",
        "v080_themed_controls": "Оформление выпадающих списков унифицировано, а текст вкладок настроек и журнала изменений увеличен.",
        "v080_update_channel": "Удалён настраиваемый канал обновлений; проверка использует встроенные источники.",
        "v080_fixed_title": "Исправлено",
        "v080_recycle_button": "Исправлено неправильное оформление кнопки «Переместить в корзину».",
        "v080_unicode_paths": "Исправлены сбои различных функций, возникавшие, когда программа находилась в пути с китайскими символами.",
        "v070_added_title": "Добавлено",
        "v070_fixed_title": "Исправлено",
        "v065_added_title": "Добавлено",
        "v065_adjusted_title": "Изменено",
        "v065_fixed_title": "Исправлено",
        "v060_added_title": "Добавлено",
        "v060_adjusted_title": "Изменено",
        "v060_fixed_title": "Исправлено",
        "v050_added_title": "Добавлено",
        "v050_adjusted_title": "Изменено",
        "v050_fixed_title": "Исправлено",
        "v030_added_title": "Добавлено",
        "v030_fixed_title": "Исправлено",
        "v020_added_title": "Добавлено",
        "v020_fixed_title": "Исправлено",
        "v010_added_title": "Добавлено",
        "v080_games_title": "Поддержка игр",
        "v080_three_kingdoms": "Добавлен выбор Total War: THREE KINGDOMS и поиск путей; папки каждой игры сохраняются при переключении.",
        "v080_workshop_title": "Публикация в Мастерской",
        "v080_workshop_ownership": "Кнопка обновления показывается только для проектов Мастерской текущей учётной записи; можно обновлять и свои подписанные MOD вне Data.",
        "v080_publish_simplified": "В публикации больше не нужно выбирать обложку или подтверждать владение: автоматически используется одноимённая PNG-обложка Pack.",
        "v080_startup_title": "Подсказки при запуске",
        "v080_startup_guidance": "Перед запуском проверяются необходимые компоненты, а при отсутствии открывается официальная инструкция по загрузке, чтобы избежать пустого окна.",
        "v080_shortcuts_title": "Горячие клавиши",
        "v080_shortcuts": "Добавлены горячие клавиши: Shift+W открывает Мастерскую, Shift+R — RPFM, Shift+E переключает включение, Shift+Enter запускает игру.",
        "v070_single_entity_unit_rule": "Добавлена настройка одиночных юнитов: можно выбрать здоровье или масштаб; режим здоровья увеличивает только здоровье, не масштаб юнита.",
        "v070_low_consumption_stability": "Исправлена периодическая ошибка при переключении режима низкого потребления.",
        "v070_game_data_title": "Изменение игровых данных",
        "v070_unit_scale_ticks": "Исправлено несовпадение делений ползунка масштаба отрядов с выбранным значением.",
        "v070_game_data_patch_reliability": "Исправлено применение масштаба не ко всем юнитам MOD и здоровью лордов и героев.",
        "v070_workshop_publish_title": "Исправления и настройка функций",
        "v070_workshop_cover": "При публикации MOD теперь загружается одноимённая PNG-обложка вместе с Pack; размер обложки — до 1 МБ.",
        "v070_save_mods": "Исправлено чтение списка MOD из текущих сохранений для команды включения MOD из сохранения.",
        "v070_spanish_language": "Добавлена поддержка испанского языка.",
        "v065_game_data_title": "Изменение игровых данных",
        "v065_auto_patch": "Патч игровых данных автоматически проверяется при запуске игры и пересоздаётся после изменения настроек, набора, активных MOD или игровых данных.",
        "v065_unit_scale": "Масштаб отрядов теперь задаётся целым значением 1–5 на ползунке; здоровье лордов и героев можно масштабировать вместе с ним.",
        "v065_game_data_window": "Окно изменения игровых данных теперь открывается быстрее.",
        "v065_workshop_title": "Работа с Мастерской",
        "v065_author_names": "Имена авторов Мастерской отображаются надёжнее, а при временной ошибке сохраняется уже полученное имя.",
        "v065_workshop_links": "В контекстном меню MOD появились отдельные переходы в Мастерскую через браузер и клиент Steam.",
        "v065_startup_title": "Запуск игры",
        "v065_skip_intro": "Исправлен пропуск вступительных роликов: теперь он пропускает все начальные видео.",
        "v060_runtime_title": "Запуск и режим низкого потребления",
        "v060_low_consumption": "Добавлен режим низкого потребления: во время игры менеджер расходует меньше ресурсов, а после выхода автоматически восстанавливается.",
        "v060_startup_speed": "Ускорены запуск и обновление Мастерской; повторный запуск открывает существующее окно, а состояние игры определяется точнее.",
        "v060_live_detection": "Добавлено мгновенное обнаружение изменений MOD: список обновляется автоматически после установки или удаления.",
        "v060_game_data_title": "Изменение игровых данных",
        "v060_game_data_controls": "В окне изменения игровых данных можно настроить численность моделей и урон союзникам, одним нажатием создать патч; он автоматически обновляется при сохранении изменений.",
        "v060_unit_multiplier": "Подписка на Dynamic Unit Size позволяет менять численность моделей обычных отрядов, ездовых существ и машин от 0,5 до 5 раз.",
        "v060_friendly_fire": "Подписка на Dynamic No Friendly Fire позволяет отдельно отключать урон союзникам от отрядов и заклинаний, сохраняя усиления и лечение.",
        "v060_library_title": "Сохранения и управление списком MOD",
        "v060_save_actions": "Из сохранения теперь можно одним действием включить используемые MOD и сравнить их с текущим списком.",
        "v060_select_all": "Добавлены выбор всего списка через Ctrl+A и включение или отключение MOD двойным щелчком.",
        "v060_official_profiles": "Профили официального лаунчера MOD можно импортировать в новый набор или использовать для замены текущего.",
        "v060_dependency_refresh": "Исправлено неточное обновление зависимостей Мастерской, поэтому предупреждения об отсутствующих зависимостях стали надёжнее.",
        "v060_files_title": "Файлы MOD и действия Мастерской",
        "v060_copy_path": "Пути MOD можно копировать группой, а названия MOD и файлов на панели сведений — выделять и копировать.",
        "v060_safe_delete": "Файлы MOD можно перемещать в корзину Windows, чтобы их можно было восстановить после случайного удаления.",
        "v060_unsubscribe_cleanup": "Отмена подписки теперь удаляет соответствующие файлы Мастерской и сразу обновляет список MOD.",
        "v060_force_update_wait": "Принудительное обновление теперь повторно загружает и восстанавливает отсутствующие файлы MOD из Мастерской.",
        "v050_settings_title": "Настройки и сведения о проекте",
        "v050_settings_pages": "Настройки разделены на четыре страницы: основные, функции запуска игры, интеграция ИИ и сведения о проекте.",
        "v050_about_page": "Добавлена страница проекта с версией и сведениями об обновлениях. Ссылки для загрузки ведут только на выпуски GitHub и Gitee, а для обратной связи доступны GitHub Issues и группа QQ 592799189.",
        "v050_startup_title": "Восстановление при запуске и управление списками",
        "v050_restore_last_order": "При первом запуске менеджер читает последний used_mods.txt Warhammer III и восстанавливает состояние и порядок только для установленных локально MOD, не загружая и не подписывая отсутствующие MOD.",
        "v050_drag_lists": "Списки включённых и отключённых MOD поддерживают одиночное и групповое перетаскивание с Ctrl или Shift. MOD можно переносить между списками; порядок включённых сохраняется сразу, а порядок отключённых — только на текущий сеанс.",
        "v050_button_style": "Унифицирован стиль кнопок открытия папок, повторного сканирования, обновления сведений Мастерской и открытия папки игры; название перехода к странице Мастерской также приведено к единому виду.",
        "v050_workshop_title": "Публикация в Мастерской и импорт кода",
        "v050_publish_language": "При обновлении MOD можно выбрать язык, по умолчанию совпадающий с языком интерфейса. Его смена загружает соответствующие название и описание Мастерской; если доступен только английский, он выбирается автоматически.",
        "v050_change_note": "Поле описания обновления заменено на изначально пустой журнал обновления; выбранный язык публикации передаётся через локальный патч Steamworks.",
        "v050_share_subscribe": "Импорт кода показывает MOD без подписки, подписывает их после подтверждения и восстанавливает в наборе после загрузки и повторного сканирования.",
        "v050_language_title": "Встроенные языки",
        "v050_system_language": "При первом запуске интерфейс автоматически использует системный язык, если это упрощённый китайский, английский, корейский, русский или японский; при ошибке определения и для неподдерживаемых языков используется английский.",
        "v050_builtin_languages": "Интерфейс и журнал изменений теперь доступны на упрощённом китайском, английском, корейском, русском и японском языках.",
        "v050_single_language_ui": "Тексты кнопок, заголовков, состояний и сообщений унифицированы, чтобы в интерфейсе не смешивались разные языки.",
        "v050_warning_title": "Исправления проверки и сообщений о проблемах",
        "v050_outdated_check": "Исправлено обратное сравнение времени при проверке устаревших MOD. Теперь предупреждение появляется только если MOD не обновлялся после обновления игры; пояснение уточнено, а прежние записи игнорирования остаются совместимыми.",
        "v050_enabled_dependency_scope": "Предупреждения об отсутствующих зависимостях теперь проверяются только для включённых MOD и сразу пересчитываются после включения, отключения, изменения порядка, перетаскивания между списками, смены набора или импорта.",
        "v050_dependency_cache_warning": "Если Steam временно не может прочитать часть зависимостей Мастерской, менеджер сообщает об использовании кеша и возможной неактуальности результатов; уведомление можно скрыть до конца текущего сеанса.",
        "v050_docs_title": "Документация и сведения о проекте",
        "v050_readme": "README переработан с акцентом на пользовательские функции, лишние технические подробности сокращены, а Warhammer Mod Manager и RimCrow добавлены в благодарности.",
        "v030_title": "Управление проблемами и расположение файлов",
        "v030_data_location": "Исправлено точное выделение Pack-файла MOD из папки Data в Проводнике.",
        "v030_ignore_issues": "В контекстное меню добавлено игнорирование устаревших MOD и отсутствующих зависимостей с возможностью восстановления для каждого MOD.",
        "v030_warning_window": "Кнопка предупреждений перенесена в центр заголовка включённых MOD; добавлено окно для игнорирования отдельных проблем.",
        "v020_title": "Обновления и групповые действия",
        "v020_dual_source": "Добавлен приоритет Gitee или GitHub по языку с автоматическим переходом на второй источник.",
        "v020_context_menu": "В контекстное меню добавлено открытие расположения файла; для группового выбора показывается число элементов и отключается одиночная операция RPFM.",
        "v020_pyinstaller": "Исправлена упаковка PyInstaller одним нажатием, когда имя продукта содержит апостроф.",
        "v010_title": "Основные функции менеджера",
        "v010_playsets": "Наборы управляют включением MOD и порядком загрузки; все изменения сохраняются сразу.",
        "v010_game_workshop": "Поддерживаются продолжение игры, загрузка из списка сохранений, управление Мастерской и предупреждения об отсутствующих зависимостях.",
        "v010_updates": "Поддерживаются автоматическая проверка обновлений, проверка загрузки, безопасная замена и журнал изменений в приложении.",
    },
    "ja-JP": {
        "v088_added_title": "追加",
        "v088_dependency_action": "不足している依存関係の警告画面から、依存関係を直接購読して有効化できるようにしました。",
        "v088_adjusted_title": "調整",
        "v088_unit_formation_width": "ユニット規模の倍率を調整すると、陣形をより広くドラッグできるようになりました。",
        "v087_added_title": "追加",
        "v087_type_order": "組み込みタイプとカスタムタイプの順序を変更して保存できるようにしました。",
        "v087_type_sort": "設定したタイプ順に MOD を並べ替える機能を追加しました。",
        "v087_manual_type": "タイプのコンテキストメニューに手動入力を追加し、Shift+F で選択した MOD に適用できるようにしました。",
        "v087_adjusted_title": "調整",
        "v087_readability": "MOD 詳細、下部操作ボタン、タイプ管理、設定画面などの文字を大きくして可読性を高めました。",
        "v087_fixed_title": "修正",
        "v087_publish_modal_ui": "Workshop の公開・更新画面で、閉じるボタンとテキストエリアのサイズ変更コントロールのスタイルが一致しない問題を修正しました。",
        "v086_fixed_title": "修正",
        "v086_playset_dependencies": "必要な MOD がインストール済みでも現在のプレイセットで有効化されていない場合に、依存関係不足の警告が表示されない問題を修正しました。",
        "v086_settings_page_ui": "設定ページの UI の問題を修正しました。",
        "v085_fixed_title": "修正",
        "v085_non_ascii_launch_paths": "ゲーム本体またはワークショップのパスに中国語などの ASCII 以外の文字が含まれると起動できない問題を修正しました。",
        "v085_game_data_overhauls": "ATC、SFO などの大型オーバーホール MOD でゲームデータ変更が正常に適用されない問題を修正しました。",
        "v085_steam_friends_utf8": "Steam フレンド名に特殊文字が含まれると起動できない問題を修正しました。",
        "v082_added_title": "追加",
        "v082_batch_ai_generation": "右クリックメニューから、選択した複数の MOD の別名とメモを AI で一括生成できるようになりました。",
        "v082_search_highlight": "検索結果の強調表示モードを追加し、一覧を維持したまま非該当項目を薄く表示して最初の結果へ移動します。",
        "v082_fixed_title": "修正",
        "v082_ai_highlight_cache": "検索結果の強調表示モード切り替え後に AI 生成で MOD が見つからなくなる問題を修正し、再スキャンを不要にしました。",
        "v081_fixed_title": "修正",
        "v081_friendly_fire": "ゲームデータ変更画面に「味方への攻撃を無効化」設定を復元しました。",
        "v081_game_scoped_playsets": "プレイセットをゲームごとに保存・表示するようにし、WARHAMMER III と THREE KINGDOMS が混在しなくなりました。",
        "v081_update_restart": "更新後の自動再起動エラーを修正し、作者情報の更新失敗でマネージャーが終了しないようにしました。",
        "v081_unit_formation": "ユニット規模拡大時の陣形調整を修正し、大砲や戦鼓などが兵器ごとの牽引動物数まで重複して拡大しないようにしました。",
        "v080_added_title": "追加",
        "v080_adjusted_title": "調整",
        "v080_workshop_collection_import": "ワークショップコレクションのインポートを追加しました。不足している MOD を自動購読し、現在のプレイセットへコレクション順で追加します。",
        "v080_recruitment_capacity": "ゲームデータ変更に募集上限の調整を追加し、1～5倍または無制限を選べるようにしました。",
        "v080_editable_shortcuts": "キーボードショートカットでキーの組み合わせを変更でき、コンテキストメニューにも表示します。",
        "v080_themed_controls": "ドロップダウンのテーマを統一し、設定タブと更新履歴の文字を大きくして読みやすくしました。",
        "v080_update_channel": "設定からソフトウェア更新チャンネルを削除し、内蔵ソースで更新を確認します。",
        "v080_fixed_title": "修正",
        "v080_recycle_button": "「ごみ箱へ移動」ボタンの表示スタイルが正しくない問題を修正しました。",
        "v080_unicode_paths": "プログラムを中国語文字を含むパスに配置すると各種機能が動作しない問題を修正しました。",
        "v070_added_title": "追加",
        "v070_fixed_title": "修正",
        "v065_added_title": "追加",
        "v065_adjusted_title": "調整",
        "v065_fixed_title": "修正",
        "v060_added_title": "追加",
        "v060_adjusted_title": "調整",
        "v060_fixed_title": "修正",
        "v050_added_title": "追加",
        "v050_adjusted_title": "調整",
        "v050_fixed_title": "修正",
        "v030_added_title": "追加",
        "v030_fixed_title": "修正",
        "v020_added_title": "追加",
        "v020_fixed_title": "修正",
        "v010_added_title": "追加",
        "v080_games_title": "ゲーム対応",
        "v080_three_kingdoms": "Total War: THREE KINGDOMS の選択とパス検出を追加し、切り替えても各ゲームのフォルダーを保持します。",
        "v080_workshop_title": "ワークショップ公開",
        "v080_workshop_ownership": "更新ボタンは現在のアカウントが所有するワークショップ項目だけに表示され、Data 外の購読済み自作 MOD も更新できます。",
        "v080_publish_simplified": "公開画面で表紙の選択と所有確認が不要になり、Pack と同名の PNG 表紙を自動使用します。",
        "v080_startup_title": "起動ガイド",
        "v080_startup_guidance": "起動前に必要な実行コンポーネントを確認し、不足時は公式ダウンロード案内を表示して空白ウィンドウを減らします。",
        "v080_shortcuts_title": "キーボードショートカット",
        "v080_shortcuts": "ショートカット設定を追加しました。Shift+W でワークショップ、Shift+R で RPFM を開き、Shift+E で有効状態を切り替え、Shift+Enter でゲームを起動します。",
        "v070_single_entity_unit_rule": "単体ユニットの調整設定を追加し、体力または規模を選択できるようになりました。体力モードでは体力だけを増やし、規模は増やしません。",
        "v070_low_consumption_stability": "低消費モード切替時に断続的に発生するエラーを修正しました。",
        "v070_game_data_title": "ゲームデータ変更",
        "v070_unit_scale_ticks": "ユニット規模倍率スライダーの目盛りと選択した倍率が一致しない問題を修正しました。",
        "v070_game_data_patch_reliability": "一部の MOD でユニット規模やロード・ヒーローの体力に倍率が適用されない問題を修正しました。",
        "v070_workshop_publish_title": "機能の修正と調整",
        "v070_workshop_cover": "MOD 公開時に同名の PNG 表紙を Pack と一緒にアップロードし、表紙は 1 MB までに制限しました。",
        "v070_save_mods": "「セーブで使用した MOD を有効化」で現在のセーブの MOD 一覧を読み取れない問題を修正しました。",
        "v070_spanish_language": "スペイン語に対応しました。",
        "v065_game_data_title": "ゲームデータ変更",
        "v065_auto_patch": "ゲーム起動時にゲームデータパッチを自動確認し、関連設定、プレイセット、有効な MOD、またはゲームデータが変わると自動で再生成します。",
        "v065_unit_scale": "ユニット規模倍率を 1～5 の整数スライダーに変更し、ロードとヒーローの体力も同時に調整できるようにしました。",
        "v065_game_data_window": "ゲームデータ変更画面がより速く開くようになりました。",
        "v065_workshop_title": "ワークショップ操作",
        "v065_author_names": "ワークショップ作者名をより安定して表示し、一時的に取得できない場合も既存の名前を保持します。",
        "v065_workshop_links": "MOD の右クリックメニューから、ブラウザーと Steam クライアントのワークショップを個別に開けるようにしました。",
        "v065_startup_title": "ゲーム起動",
        "v065_skip_intro": "「オープニングムービーをスキップ」がすべての開始動画に正しく適用されるよう修正しました。",
        "v060_runtime_title": "起動と低消費モード",
        "v060_low_consumption": "ゲーム実行中の管理ツールのリソース使用量を抑え、終了後に自動復帰する低消費モードを追加しました。",
        "v060_startup_speed": "起動とワークショップ更新を改善しました。WMM を再起動すると既存画面を表示し、ゲーム状態もより正確に判定します。",
        "v060_live_detection": "MOD のインストールや削除後に一覧を自動更新する即時変更検出を追加しました。",
        "v060_game_data_title": "ゲームデータ変更",
        "v060_game_data_controls": "兵数倍率と味方ダメージを調整し、パッチを生成できるゲームデータ変更画面を追加しました。変更を保存すると自動的に更新されます。",
        "v060_unit_multiplier": "Dynamic Unit Size を購読すると、一般ユニット、騎乗物、兵器の兵数を 0.5～5 倍に調整できます。",
        "v060_friendly_fire": "Dynamic No Friendly Fire を購読すると、ユニットと呪文の味方ダメージを個別に無効化しつつ、強化と回復は維持できます。",
        "v060_library_title": "セーブと MOD 一覧操作",
        "v060_save_actions": "セーブで使用した MOD をまとめて有効化し、現在の有効一覧と比較できるようになりました。",
        "v060_select_all": "Ctrl+A の全選択と、ダブルクリックによる MOD の有効化・無効化を追加しました。",
        "v060_official_profiles": "公式 MOD ランチャーのプロファイルから、新しいプレイセットの作成や現在のプレイセットの置換ができます。",
        "v060_dependency_refresh": "ワークショップの依存関係更新を修正し、不足している依存 MOD の警告をより正確にしました。",
        "v060_files_title": "MOD ファイルとワークショップ操作",
        "v060_copy_path": "複数の MOD パスをまとめてコピーでき、詳細欄の MOD 名とファイル名も選択してコピーできます。",
        "v060_safe_delete": "MOD ファイルをごみ箱へ移動できるようになり、誤って削除しても復元できます。",
        "v060_unsubscribe_cleanup": "購読解除時に対応するワークショップファイルを削除し、MOD 一覧をすぐに更新します。",
        "v060_force_update_wait": "強制更新で不足しているワークショップ MOD ファイルを再ダウンロードして復元できるようになりました。",
        "v050_settings_title": "設定とプロジェクト情報",
        "v050_settings_pages": "設定画面を基本設定、機能（ゲーム起動の拡張）、AI 統合、プロジェクト情報の4ページに分割しました。",
        "v050_about_page": "バージョンと更新情報をまとめたプロジェクト情報ページを追加しました。ダウンロード先は GitHub と Gitee のリリースページだけにし、フィードバックと交流には GitHub Issues と QQ グループ 592799189 を案内します。",
        "v050_startup_title": "起動時の復元と一覧操作",
        "v050_restore_last_order": "初回起動時に Warhammer III が最後に使用した used_mods.txt を読み、ローカルにインストール済みの MOD だけを有効状態と読み込み順へ復元します。不足 MOD のダウンロードや購読は行いません。",
        "v050_drag_lists": "有効・無効の両 MOD 一覧で、単一および Ctrl・Shift による複数ドラッグに対応しました。一覧間の移動が可能で、有効順は即時保存、無効順は現在の実行中のみ保持します。",
        "v050_button_style": "フォルダーを開く、再スキャン、ワークショップ情報の更新、ゲームフォルダーを開くなどのボタンスタイルを統一し、ページ入口の名称もワークショップページに統一しました。",
        "v050_workshop_title": "ワークショップ公開と共有コードのインポート",
        "v050_publish_language": "MOD 更新の公開言語を選択でき、初期値には現在の表示言語を使用します。言語を切り替えると対応するワークショップタイトルと説明を読み込み、英語しかない場合は自動的に英語を使用します。",
        "v050_change_note": "更新説明を初期状態が空の更新ログに変更し、ローカル Steamworks パッチから選択した公開言語を書き込むようにしました。",
        "v050_share_subscribe": "共有コードのインポート時に未購読 MOD を表示し、確認後に自動購読します。ダウンロード後の再スキャンでプレイセットへ復元します。",
        "v050_language_title": "内蔵多言語",
        "v050_system_language": "初回起動時、システム言語が簡体字中国語、英語、韓国語、ロシア語、日本語のいずれかなら自動選択し、検出失敗または未対応言語の場合は英語を既定値にします。",
        "v050_builtin_languages": "画面と更新履歴に簡体字中国語、英語、韓国語、ロシア語、日本語を内蔵しました。",
        "v050_single_language_ui": "選択した表示言語に別の言語が混ざらないよう、ボタン、見出し、状態、通知文を統一しました。",
        "v050_warning_title": "警告判定と案内の修正",
        "v050_outdated_check": "古い MOD の判定で更新時刻の比較方向が逆だった問題を修正しました。ゲーム本体の更新後に MOD が更新されていない場合だけ警告し、説明文を明確化するとともに旧版の無視設定も引き継ぎます。",
        "v050_enabled_dependency_scope": "依存関係不足の警告は有効な MOD だけを対象とし、有効化、無効化、並べ替え、一覧間のドラッグ、プレイセット切り替え、インポートの直後に再判定するようにしました。",
        "v050_dependency_cache_warning": "Steam が一部のワークショップ依存関係を一時的に取得できない場合、キャッシュ使用中で依存関係不足の結果が最新でない可能性を明示し、今回の実行中は通知を無視できるようにしました。",
        "v050_docs_title": "ドキュメントとプロジェクト情報",
        "v050_readme": "README をユーザー向け機能中心に整理し、不要な実装詳細を減らし、Warhammer Mod Manager と RimCrow への謝辞を追加しました。",
        "v030_title": "問題管理とファイル位置",
        "v030_data_location": "Data フォルダー内の MOD の Pack ファイルをエクスプローラーで正確に選択できない問題を修正しました。",
        "v030_ignore_issues": "右クリックメニューに問題を無視する機能を追加し、MOD ごとに古さと依存関係不足の警告を無視・復元できます。",
        "v030_warning_window": "警告入口を有効な MOD の見出し中央へ移動し、個別の問題を無視できる中央ウィンドウを追加しました。",
        "v020_title": "更新と一括操作",
        "v020_dual_source": "現在の言語に応じて Gitee または GitHub を優先確認し、自動的に代替ソースへ切り替えるようにしました。",
        "v020_context_menu": "右クリックメニューにファイルの場所を開く操作を追加しました。複数選択時は件数を表示し、単一項目用の RPFM 操作を無効にします。",
        "v020_pyinstaller": "製品名にアポストロフィがある場合に PyInstaller のワンクリックパッケージが失敗する問題を修正しました。",
        "v010_title": "マネージャーの基本機能",
        "v010_playsets": "プレイセットで MOD の有効状態と読み込み順を管理し、すべての変更を即時保存します。",
        "v010_game_workshop": "ゲームの続行、セーブ一覧からの読み込み、ワークショップ管理、依存関係不足の警告に対応しました。",
        "v010_updates": "更新の自動確認、ダウンロード検証、安全な置換、アプリ内更新履歴に対応しました。",
    },
    "es-ES": {
        "v088_added_title": "Añadido",
        "v088_dependency_action": "La advertencia de dependencias faltantes ahora permite suscribirse y activarlas directamente.",
        "v088_adjusted_title": "Ajustado",
        "v088_unit_formation_width": "Los multiplicadores del tamaño de unidad ahora también permiten arrastrar las formaciones más anchas.",
        "v087_added_title": "Añadido",
        "v087_type_order": "La gestión de tipos ahora permite reordenar y guardar los tipos integrados y personalizados.",
        "v087_type_sort": "Se añadió la clasificación de MOD por el orden configurado de tipos.",
        "v087_manual_type": "Se añadió Entrada manual al menú contextual de tipos, con Shift+F para aplicarla a los MOD seleccionados.",
        "v087_adjusted_title": "Ajustado",
        "v087_readability": "Se amplió el texto de los detalles del MOD, los botones inferiores, la gestión de tipos y Configuración.",
        "v087_fixed_title": "Corregido",
        "v087_publish_modal_ui": "Se corrigieron los estilos incoherentes del botón de cierre y del control de tamaño de texto en la ventana de publicación/actualización del Taller.",
        "v086_fixed_title": "Corregido",
        "v086_playset_dependencies": "Se corrigió la falta de aviso de dependencia cuando el MOD requerido está instalado pero no está habilitado en el conjunto actual.",
        "v086_settings_page_ui": "Se corrigieron problemas de interfaz en la página de configuración.",
        "v085_fixed_title": "Corregido",
        "v085_non_ascii_launch_paths": "Se corrigió el inicio del juego cuando la instalación o la carpeta de Workshop contiene caracteres chinos u otros caracteres no ASCII.",
        "v085_game_data_overhauls": "Se corrigió el funcionamiento incorrecto de la modificación de datos del juego con grandes MOD, como ATC y SFO.",
        "v085_steam_friends_utf8": "Se corrigió el fallo de inicio cuando el nombre de un amigo de Steam contiene caracteres especiales.",
        "v082_added_title": "Añadido",
        "v082_batch_ai_generation": "El menú contextual ahora puede usar IA para generar alias y notas para varios MOD seleccionados.",
        "v082_search_highlight": "La búsqueda incluye un modo de resaltado que conserva la lista completa, atenúa los demás MOD y salta al primer resultado.",
        "v082_fixed_title": "Correcciones",
        "v082_ai_highlight_cache": "Se corrigió el error por el que la IA no encontraba MOD tras activar el resaltado; ya no es necesario volver a escanear.",
        "v081_fixed_title": "Correcciones",
        "v081_friendly_fire": "Se restauró el ajuste para eliminar el fuego amigo en Modificación de datos del juego.",
        "v081_game_scoped_playsets": "Los conjuntos se guardan y se muestran por juego para que WARHAMMER III y THREE KINGDOMS no se mezclen.",
        "v081_update_restart": "Se corrigió el reinicio tras actualizar y se evitó que un fallo al actualizar autores cierre el gestor.",
        "v081_unit_formation": "Se corrigió el ajuste de formaciones y se evitó que cañones, tambores de guerra y otras máquinas multipliquen de nuevo sus monturas de tiro por máquina.",
        "v080_added_title": "Añadido",
        "v080_adjusted_title": "Ajustado",
        "v080_workshop_collection_import": "Se añadió la importación de colecciones del Taller: los MOD faltantes se suscriben automáticamente y el conjunto actual conserva el orden de la colección.",
        "v080_recruitment_capacity": "Se añadió el ajuste de capacidad de reclutamiento en los datos del juego, con opciones de 1–5× o ilimitada.",
        "v080_editable_shortcuts": "Los atajos admiten combinaciones personalizadas y se muestran también en el menú contextual.",
        "v080_themed_controls": "Se unificó el estilo de los desplegables y se amplió el texto de las pestañas de ajustes y del registro de cambios.",
        "v080_update_channel": "Se eliminó el canal de actualización configurable; las comprobaciones usan las fuentes integradas.",
        "v080_fixed_title": "Corregido",
        "v080_recycle_button": "Se corrigió el estilo incorrecto del botón «Mover a la papelera de reciclaje».",
        "v080_unicode_paths": "Se corrigieron varios fallos de funciones cuando el programa se encuentra en una ruta con caracteres chinos.",
        "v070_added_title": "Añadido",
        "v070_fixed_title": "Corregido",
        "v065_added_title": "Añadido",
        "v065_adjusted_title": "Ajustado",
        "v065_fixed_title": "Corregido",
        "v060_added_title": "Añadido",
        "v060_adjusted_title": "Ajustado",
        "v060_fixed_title": "Corregido",
        "v050_added_title": "Añadido",
        "v050_adjusted_title": "Ajustado",
        "v050_fixed_title": "Corregido",
        "v030_added_title": "Añadido",
        "v030_fixed_title": "Corregido",
        "v020_added_title": "Añadido",
        "v020_fixed_title": "Corregido",
        "v010_added_title": "Añadido",
        "v080_games_title": "Compatibilidad con juegos",
        "v080_three_kingdoms": "Se añadieron la selección y detección de rutas de Total War: THREE KINGDOMS; las carpetas de cada juego se conservan al cambiar.",
        "v080_workshop_title": "Publicación en el Taller",
        "v080_workshop_ownership": "Las actualizaciones solo se muestran para proyectos del Taller propiedad de la cuenta actual; los MOD propios suscritos fuera de Data también se pueden actualizar.",
        "v080_publish_simplified": "Publicar ya no pide elegir portada ni confirmar propiedad y usa automáticamente la portada PNG con el mismo nombre que el Pack.",
        "v080_startup_title": "Guía de inicio",
        "v080_startup_guidance": "Antes de iniciar se comprueban los componentes necesarios y, si falta alguno, se ofrece la guía oficial de descarga para reducir las ventanas en blanco.",
        "v080_shortcuts_title": "Atajos de teclado",
        "v080_shortcuts": "Se añadieron atajos: Shift+W abre el Taller, Shift+R abre RPFM, Shift+E alterna el estado activado y Shift+Enter inicia el juego.",
        "v070_single_entity_unit_rule": "Se añadió un ajuste para unidades de una sola entidad: permite elegir salud o tamaño; el modo Salud aumenta solo la salud, no el tamaño.",
        "v070_low_consumption_stability": "Se corrigió un error ocasional al cambiar de modo de bajo consumo.",
        "v070_game_data_title": "Modificación de datos del juego",
        "v070_unit_scale_ticks": "Se corrigieron las marcas del control de escala de unidades que no coincidían con el multiplicador seleccionado.",
        "v070_game_data_patch_reliability": "Se corrigió que el escalado no se aplicara a algunas unidades MOD ni a la salud de señores y héroes.",
        "v070_workshop_publish_title": "Correcciones y ajustes de funciones",
        "v070_workshop_cover": "Al publicar un MOD, ahora se sube una portada PNG del mismo nombre junto con el Pack; el límite de la portada es 1 MB.",
        "v070_save_mods": "Se corrigió la lectura de MODs de las partidas actuales al usar «Activar MODs usados en la partida».",
        "v070_spanish_language": "Se añadió compatibilidad con español.",
        "v065_game_data_title": "Modificación de datos del juego",
        "v065_auto_patch": "El parche se verifica al iniciar el juego y se regenera al cambiar ajustes, conjuntos, MODs activos o datos del juego.",
        "v065_unit_scale": "La escala de unidades ahora usa un control deslizante entero de 1–5, con una opción para escalar la salud de señores y héroes.",
        "v065_game_data_window": "La ventana de modificación de datos del juego ahora se abre más rápido.",
        "v065_workshop_title": "Experiencia del Taller",
        "v065_author_names": "Los nombres de autores del Taller son más fiables; los ya obtenidos se conservan si una actualización falla temporalmente.",
        "v065_workshop_links": "Los menús contextuales de MOD incluyen enlaces separados al Taller en el navegador y en Steam.",
        "v065_startup_title": "Inicio del juego",
        "v065_skip_intro": "Se corrigió «Saltar introducción» para omitir todas las cinemáticas iniciales.",
        "v060_runtime_title": "Inicio y modo de bajo consumo",
        "v060_low_consumption": "Se añadió un modo de bajo consumo que reduce los recursos del gestor mientras el juego está en ejecución y los restaura al cerrarlo.",
        "v060_startup_speed": "Se mejoraron el inicio y la actualización del Taller; al reabrir WMM se activa la ventana existente y la detección del juego es más precisa.",
        "v060_live_detection": "Se añadió detección de cambios de MOD en tiempo real para actualizar la lista automáticamente al instalar o eliminar MODs.",
        "v060_game_data_title": "Modificación de datos del juego",
        "v060_game_data_controls": "Se añadió una ventana para ajustar modelos y fuego amigo; permite generar el parche con un clic y se actualiza automáticamente al guardar los cambios.",
        "v060_unit_multiplier": "Suscríbete a Dynamic Unit Size para ajustar los modelos de unidades normales, monturas y máquinas de guerra de 0,5× a 5×.",
        "v060_friendly_fire": "Suscríbete a Dynamic No Friendly Fire para desactivar por separado el fuego amigo de unidades y hechizos, conservando mejoras y curación para aliados.",
        "v060_library_title": "Partidas guardadas y lista de MODs",
        "v060_save_actions": "Las partidas guardadas pueden activar sus MODs con un clic y compararlos con la lista activa.",
        "v060_select_all": "Se añadieron Ctrl+A y doble clic para activar o desactivar MODs más rápidamente.",
        "v060_official_profiles": "Los perfiles del lanzador oficial pueden crear un conjunto nuevo o reemplazar el actual.",
        "v060_dependency_refresh": "Se corrigió la actualización de dependencias del Taller para que los avisos de dependencias faltantes sean más fiables.",
        "v060_files_title": "Archivos MOD y acciones del Taller",
        "v060_copy_path": "Se pueden copiar rutas de MOD por lotes, y seleccionar y copiar nombres de MOD y archivos en el panel de detalles.",
        "v060_safe_delete": "Los archivos MOD se pueden mover a la Papelera de reciclaje de Windows para recuperarlos tras un borrado accidental.",
        "v060_unsubscribe_cleanup": "Al cancelar la suscripción se limpian los archivos correspondientes del Taller y se actualiza la lista de MODs.",
        "v060_force_update_wait": "Actualización forzada puede volver a descargar y restaurar archivos MOD del Taller que faltan.",
        "v050_settings_title": "Configuración e información del proyecto",
        "v050_settings_pages": "La configuración se divide en Básica, Funciones, Integración de IA y Acerca de.",
        "v050_about_page": "Se añadió una página Acerca de con versiones y actualizaciones. Las descargas apuntan a GitHub y Gitee; comentarios y debates usan GitHub Issues y el grupo QQ 592799189.",
        "v050_startup_title": "Recuperación de inicio y controles de lista",
        "v050_restore_last_order": "En el primer inicio, el gestor lee el último used_mods.txt de Warhammer III y restaura el estado activo y el orden de carga de los MODs instalados localmente. Nunca descarga ni suscribe automáticamente MODs faltantes.",
        "v050_drag_lists": "Los MODs activos e inactivos admiten arrastre por lotes con clic, Ctrl y Shift. Pueden moverse entre listas; el orden activo se guarda al instante y el inactivo dura solo durante la sesión.",
        "v050_button_style": "Se unificaron las acciones de directorios, reanálisis, Taller y actualización del directorio del juego, incluidos sus nombres.",
        "v050_workshop_title": "Publicación en el Taller e importación de códigos compartidos",
        "v050_publish_language": "Al publicar una actualización de MOD se puede elegir el idioma, que por defecto es el de la interfaz. Al cambiarlo se carga el título y la descripción del Taller, con respaldo en inglés si solo existe contenido en inglés.",
        "v050_change_note": "Se cambió «Notas de actualización» por «Registro de actualización», inicialmente vacío, y se añadió el idioma de publicación seleccionado.",
        "v050_share_subscribe": "La importación de códigos compartidos muestra MODs sin suscripción, los suscribe tras confirmación y los restaura en el conjunto después de descargarlos y reanalizarlos.",
        "v050_language_title": "Idiomas integrados",
        "v050_system_language": "En el primer inicio, la interfaz sigue el idioma del sistema si es chino simplificado, inglés, coreano, ruso o japonés; los errores de detección y los idiomas no compatibles usan inglés.",
        "v050_builtin_languages": "La interfaz y el registro de cambios incluyen chino simplificado, inglés, coreano, ruso y japonés.",
        "v050_single_language_ui": "Se unificaron botones, encabezados, estados y avisos para que la interfaz seleccionada no mezcle idiomas.",
        "v050_warning_title": "Detección de advertencias y corrección de mensajes",
        "v050_outdated_check": "Se corrigió la comparación invertida de fechas para MODs desactualizados. El aviso aparece solo cuando un MOD no se actualizó desde el juego y se conservan los avisos ignorados.",
        "v050_enabled_dependency_scope": "Los avisos de dependencias faltantes se aplican solo a MODs activos y se recalculan al activar, desactivar, reordenar, arrastrar, cambiar de conjunto o importar.",
        "v050_dependency_cache_warning": "Si Steam no puede leer algunas dependencias del Taller, el gestor explica que usa datos en caché y que los resultados pueden estar desactualizados; el aviso se puede ignorar durante la sesión.",
        "v050_docs_title": "Documentación e información del proyecto",
        "v050_readme": "Se reorganizó el README alrededor de funciones para usuarios, se quitaron detalles innecesarios y se añadieron agradecimientos a Warhammer Mod Manager y RimCrow.",
        "v030_title": "Gestión de problemas y ubicación de archivos",
        "v030_data_location": "Se corrigió la ubicación de archivos Pack de MODs almacenados en Data desde el Explorador de archivos.",
        "v030_ignore_issues": "Se añadió «Ignorar problema» al menú contextual para ignorar o restaurar avisos de MODs desactualizados y dependencias faltantes.",
        "v030_warning_window": "La entrada de advertencias se movió al centro del encabezado de MODs activos y se añadió una ventana centrada para ignorar problemas individuales.",
        "v020_title": "Actualizaciones y acciones por lotes",
        "v020_dual_source": "Se añadió prioridad de actualización según el idioma entre Gitee y GitHub, con respaldo automático.",
        "v020_context_menu": "Se añadió «Abrir ubicación del archivo» al menú contextual; las selecciones por lotes muestran el número de elementos y desactivan la acción RPFM individual.",
        "v020_pyinstaller": "Se corrigió el empaquetado con un clic de PyInstaller cuando el nombre del producto contiene un apóstrofo.",
        "v010_title": "Funciones básicas del gestor",
        "v010_playsets": "Gestiona MODs activos y el orden de carga con conjuntos; todos los cambios se guardan inmediatamente.",
        "v010_game_workshop": "Permite continuar partidas, cargar desde la lista de guardados, gestionar el Taller y avisar de dependencias faltantes.",
        "v010_updates": "Incluye comprobación automática de actualizaciones, descargas verificadas, reemplazo seguro y registro de cambios dentro de la aplicación.",
    },
}


def _build_changelog(language: str) -> list[dict[str, Any]]:
    catalog = CHANGELOG_TEXT[language]
    releases: list[dict[str, Any]] = []
    for release in CHANGELOG_STRUCTURE:
        entries = []
        for title_key, changes_spec in release["entries"]:
            entries.append(
                {
                    "title": catalog[title_key],
                    "changes": [
                        {"type": change_type, "text": catalog[text_key]}
                        for change_type, text_key in changes_spec
                    ],
                }
            )
        releases.append(
            {
                "version": release["version"],
                "date": release["date"],
                "entries": entries,
            }
        )
    return releases


APP_CHANGELOG: list[dict[str, Any]] = _build_changelog(DEFAULT_CHANGELOG_LANGUAGE)


def get_all_changelogs(language: str = DEFAULT_CHANGELOG_LANGUAGE) -> list[dict[str, Any]]:
    """Return an isolated changelog in one of the built-in interface languages."""
    normalized = language if language in SUPPORTED_CHANGELOG_LANGUAGES else DEFAULT_CHANGELOG_LANGUAGE
    return deepcopy(_build_changelog(normalized))
