"""Read-only WH3 UI tables, verified against the local RPFM schema (2026-09-27)."""

ENCYCLOPEDIA_SCHEMAS = {'unit_variants_tables': {5: (('faction', 'OptionalStringU8'),
                              ('name', 'StringU8'),
                              ('unit', 'StringU8'),
                              ('variant', 'StringU8'),
                              ('unit_card', 'StringU8'))},
 'ui_unit_groupings_tables': {1: (('icon', 'StringU8'), ('key', 'StringU8'), ('parent_group', 'StringU8'))},
 'unit_attributes_to_groups_junctions_tables': {2: (('attribute', 'StringU8'),
                                                    ('attribute_group', 'OptionalStringU8'))},
 'unit_abilities_tables': {17: (('key', 'StringU8'),
                                ('requires_effect_enabling', 'Boolean'),
                                ('icon_name', 'StringU8'),
                                ('overpower_option', 'OptionalStringU8'),
                                ('type', 'StringU8'),
                                ('video', 'OptionalStringU8'),
                                ('uniqueness', 'StringU8'),
                                ('is_unit_upgrade', 'Boolean'),
                                ('is_hidden_in_ui', 'Boolean'),
                                ('source_type', 'StringU8'),
                                ('superseded_abilities_set', 'OptionalStringU8'),
                                ('is_hidden_in_ui_for_enemy', 'Boolean')),
                           16: (('key', 'StringU8'),
                                ('requires_effect_enabling', 'Boolean'),
                                ('icon_name', 'StringU8'),
                                ('overpower_option', 'OptionalStringU8'),
                                ('type', 'StringU8'),
                                ('video', 'OptionalStringU8'),
                                ('uniqueness', 'StringU8'),
                                ('is_unit_upgrade', 'Boolean'),
                                ('is_hidden_in_ui', 'Boolean'),
                                ('source_type', 'StringU8'),
                                ('superseded_abilities_set', 'OptionalStringU8'),
                                ('is_hidden_in_ui_for_enemy', 'Boolean')),
                           15: (('key', 'StringU8'),
                                ('requires_effect_enabling', 'Boolean'),
                                ('icon_name', 'StringU8'),
                                ('overpower_option', 'OptionalStringU8'),
                                ('type', 'StringU8'),
                                ('video', 'OptionalStringU8'),
                                ('uniqueness', 'StringU8'),
                                ('is_unit_upgrade', 'Boolean'),
                                ('is_hidden_in_ui', 'Boolean'),
                                ('source_type', 'StringU8'),
                                ('superseded_abilities_set', 'OptionalStringU8')),
                           14: (('key', 'StringU8'),
                                ('supersedes_ability', 'OptionalStringU8'),
                                ('requires_effect_enabling', 'Boolean'),
                                ('icon_name', 'StringU8'),
                                ('overpower_option', 'OptionalStringU8'),
                                ('type', 'StringU8'),
                                ('video', 'OptionalStringU8'),
                                ('uniqueness', 'StringU8'),
                                ('is_unit_upgrade', 'Boolean'),
                                ('is_hidden_in_ui', 'Boolean'),
                                ('source_type', 'StringU8')),
                           13: (('key', 'StringU8'),
                                ('supersedes_ability', 'OptionalStringU8'),
                                ('requires_effect_enabling', 'Boolean'),
                                ('icon_name', 'StringU8'),
                                ('overpower_option', 'OptionalStringU8'),
                                ('type', 'StringU8'),
                                ('video', 'OptionalStringU8'),
                                ('uniqueness', 'StringU8'),
                                ('is_unit_upgrade', 'Boolean'),
                                ('is_hidden_in_ui', 'Boolean'))},
 'land_units_to_unit_abilites_junctions_tables': {1: (('ability', 'StringU8'),
                                                      ('land_unit', 'StringU8'),
                                                      ('culture', 'StringU8')),
                                                  0: (('ability', 'StringU8'), ('land_unit', 'StringU8'))},
 'unit_shield_types_tables': {6: (('key', 'StringU8'),
                                  ('shield_defence_value', 'I32'),
                                  ('shield_armour_value', 'I32'),
                                  ('missile_block_chance', 'I32'),
                                  ('audio_type', 'OptionalStringU8'))}}
