// Keep catalogue text aligned with the six built-in interface languages.
export const encyclopediaEntries = {
  'encyclopedia.title': ['单位图鉴', 'Unit encyclopedia', '유닛 도감', 'Энциклопедия отрядов', 'ユニット図鑑', 'Enciclopedia de unidades'],
  'encyclopedia.chooseFaction': ['选择派系', 'Choose a faction', '세력 선택', 'Выберите фракцию', '勢力を選択', 'Elegir facción'],
  'encyclopedia.back': ['选择派系', 'Factions', '세력 목록', 'Фракции', '勢力一覧', 'Facciones'],
  'encyclopedia.navigation': ['图鉴导航', 'Catalogue navigation', '도감 탐색', 'Навигация по энциклопедии', '図鑑ナビゲーション', 'Navegación de la enciclopedia'],
  'encyclopedia.search': ['搜索图鉴', 'Search catalogue', '도감 검색', 'Поиск в энциклопедии', '図鑑を検索', 'Buscar en la enciclopedia'],
  'encyclopedia.searchUnits': ['搜索单位名称或 Key…', 'Search units by name or key…', '유닛 이름 또는 키 검색…', 'Название или ключ отряда…', 'ユニット名・キーを検索…', 'Buscar nombre o clave de unidad…'],
  'encyclopedia.searchFactions': ['搜索派系…', 'Search factions…', '세력 검색…', 'Поиск фракций…', '勢力を検索…', 'Buscar facciones…'],
  'encyclopedia.count': ['{count} 个单位', '{count} units', '유닛 {count}개', 'Отрядов: {count}', '{count} ユニット', '{count} unidades'],
  'encyclopedia.sources': ['原版与当前 MOD · {count} 个 Pack', 'Base game & current MODs · {count} Packs', '원본 및 현재 MOD · Pack {count}개', 'Оригинал и текущие MOD · Pack: {count}', '原版と現在の MOD · {count} Pack', 'Juego base y MODs actuales · {count} Packs'],
  'encyclopedia.refresh': ['重新读取', 'Reload', '다시 읽기', 'Обновить', '再読み込み', 'Recargar'],
  'encyclopedia.retry': ['重试', 'Retry', '재시도', 'Повторить', '再試行', 'Reintentar'],
  'encyclopedia.loading': ['正在读取当前 MOD 列表、单位数据和原版素材…', 'Reading the current MOD list, unit data and original art…', '현재 MOD 목록, 유닛 데이터 및 원본 이미지를 읽는 중…', 'Чтение текущего списка MOD, данных отрядов и изображений…', '現在の MOD リスト・ユニットデータ・原版素材を読み込み中…', 'Leyendo la lista actual de MODs, datos e imágenes originales…'],
  'encyclopedia.empty': ['没有符合条件的内容', 'No matches', '일치하는 항목 없음', 'Ничего не найдено', '該当する項目はありません', 'No hay resultados'],
  'encyclopedia.unassigned': ['其他单位', 'Other units', '기타 유닛', 'Другие отряды', 'その他のユニット', 'Otras unidades'],
  'encyclopedia.prologueName': ['{name}（序章）', '{name} (Prologue)', '{name} (프롤로그)', '{name} (Пролог)', '{name}（序章）', '{name} (Prólogo)'],
  'encyclopedia.detail': ['单位详情', 'Unit details', '유닛 정보', 'Сведения об отряде', 'ユニット詳細', 'Detalles de la unidad'],
  'encyclopedia.edit': ['修改', 'Edit', '수정', 'Изменить', '編集', 'Editar'],
  'encyclopedia.editUnit': ['修改「{name}」的单位数据', 'Edit unit data for {name}', '{name} 유닛 데이터 수정', 'Изменить данные отряда «{name}»', '「{name}」のユニットデータを編集', 'Editar los datos de {name}'],
  'encyclopedia.selectUnit': ['选择一个单位查看详情', 'Select a unit to view its details', '정보를 볼 유닛을 선택하세요', 'Выберите отряд для просмотра', 'ユニットを選ぶと詳細を表示します', 'Selecciona una unidad para ver sus detalles'],
  'encyclopedia.models': ['部队人数', 'Unit size', '부대 인원', 'Размер отряда', '部隊人数', 'Tamaño de unidad'],
  'encyclopedia.weaponStrength': ['武器威力', 'Weapon strength', '무기 피해', 'Урон оружием', '武器強度', 'Fuerza del arma'],
  'encyclopedia.missileStrength': ['单发远程伤害', 'Missile damage per shot', '발당 사격 피해', 'Урон за выстрел', '射撃一発のダメージ', 'Daño por disparo'],
  'encyclopedia.damageParts': ['近战：基础 {base} · 破甲 {ap}', 'Melee: base {base} · AP {ap}', '근접: 기본 {base} · 관통 {ap}', 'Ближний бой: базовый {base} · ББ {ap}', '近接：基本 {base} · 徹甲 {ap}', 'Cuerpo a cuerpo: base {base} · perforación {ap}'],
  'encyclopedia.rangedParts': ['远程：基础 {base} · 破甲 {ap}', 'Ranged: base {base} · AP {ap}', '사격: 기본 {base} · 관통 {ap}', 'Стрельба: базовый {base} · ББ {ap}', '射撃：基本 {base} · 徹甲 {ap}', 'A distancia: base {base} · perforación {ap}'],
  'encyclopedia.features': ['部队属性与能力', 'Attributes & abilities', '특성 및 능력', 'Свойства и способности', '部隊の特性と能力', 'Atributos y habilidades'],
  'encyclopedia.characters': ['领主与英雄', 'Lords & heroes', '군주 및 영웅', 'Лорды и герои', 'ロードとヒーロー', 'Señores y héroes'],
  'encyclopedia.regularUnits': ['普通单位', 'Regular units', '일반 유닛', 'Обычные отряды', '一般ユニット', 'Unidades regulares'],
  'encyclopedia.rosterPages': ['单位分类', 'Roster categories', '유닛 분류', 'Категории отрядов', 'ユニット分類', 'Categorías de unidades'],
  'encyclopedia.firingInterval': ['射击间隔（基础）', 'Firing interval (base)', '사격 간격 (기본)', 'Интервал стрельбы (базовый)', '射撃間隔（基本）', 'Intervalo de disparo (base)'],
  'encyclopedia.firingIntervalHelp': ['投射物的基础装填时间，不含装填技能和射击动画带来的变化。', 'Base projectile reload time, before reload skill and firing animation adjustments.', '재장전 능력과 사격 애니메이션의 영향을 제외한 기본 재장전 시간입니다.', 'Базовое время перезарядки без поправок на навык и анимацию стрельбы.', 'リロード技能と射撃アニメーションによる変化を含まない基本装填時間です。', 'Tiempo base de recarga, sin ajustes por habilidad ni animación de disparo.'],
  'encyclopedia.projectileCount': ['弹丸数', 'Projectile count', '투사체 수', 'Число снарядов', '投射体数', 'Número de proyectiles'],
  'encyclopedia.projectileCountHelp': ['每次发射的弹丸数量，不是整支部队齐射的总数。', 'Projectiles per launch, excluding the total unit volley.', '한 번 발사할 때의 투사체 수이며 부대 전체의 일제사격 합계가 아닙니다.', 'Число снарядов за один выстрел, без суммирования залпа всего отряда.', '一回の発射で放つ投射体の数。部隊全体の一斉射撃の総数は含みません。', 'Proyectiles por disparo, sin sumar la salva de toda la unidad.'],
  'encyclopedia.seconds': ['{value} 秒', '{value} s', '{value}초', '{value} с', '{value} 秒', '{value} s'],
  'encyclopedia.source': ['数据来源', 'Data sources', '데이터 출처', 'Источники данных', 'データの出典', 'Fuentes de datos'],
  'encyclopedia.edited': ['已应用保存的单位数据修改', 'Saved unit edits applied', '저장된 유닛 수정 적용됨', 'Применены сохранённые изменения', '保存済みのユニット変更を適用', 'Cambios guardados de unidades aplicados'],
  'encyclopedia.basis': ['当前加载顺序下的数据库基础属性，含已保存的单位修改；不含战役加成和游戏内兵力规模调整。', 'Base database stats in the current load order, including saved unit edits; excludes campaign bonuses and in-game unit-size scaling.', '현재 로드 순서의 기본 DB 능력치 및 저장된 수정입니다. 캠페인 보너스와 게임 내 부대 규모 조정은 제외됩니다.', 'Базовые параметры БД с текущим порядком загрузки и сохранёнными правками; без бонусов кампании и масштаба отрядов из настроек игры.', '現在の読込順の基礎データと保存済みの変更を表示。キャンペーン補正・ゲーム内の部隊規模設定は含みません。', 'Valores base con el orden de carga actual y cambios guardados; sin bonificaciones de campaña ni ajustes de tamaño de unidad del juego.'],
  'encyclopedia.noImage': ['该单位未提供可读取的兵牌', 'No readable unit card is available', '읽을 수 있는 유닛 카드 없음', 'Изображение отряда недоступно', '兵牌画像を読み込めません', 'No hay una imagen de unidad disponible'],
  'encyclopedia.imageWarning': ['部分素材暂时无法读取，单位数据仍可浏览。', 'Some images could not be read. Unit data remains available.', '일부 이미지를 읽을 수 없습니다. 유닛 데이터는 볼 수 있습니다.', 'Некоторые изображения недоступны. Данные отрядов доступны.', '一部の素材を読み込めません。ユニットデータは閲覧できます。', 'No se pudieron leer algunas imágenes. Los datos siguen disponibles.'],
  'encyclopedia.lords': ['领主', 'Lords', '군주', 'Лорды', 'ロード', 'Señores'],
  'encyclopedia.heroes': ['英雄', 'Heroes', '영웅', 'Герои', 'ヒーロー', 'Héroes'],
  'encyclopedia.infantry': ['步兵', 'Infantry', '보병', 'Пехота', '歩兵', 'Infantería'],
  'encyclopedia.missileInfantry': ['远程步兵', 'Missile infantry', '사격 보병', 'Стрелковая пехота', '遠隔歩兵', 'Infantería de proyectiles'],
  'encyclopedia.cavalry': ['骑兵与战车', 'Cavalry & chariots', '기병 및 전차', 'Кавалерия и колесницы', '騎兵と戦車', 'Caballería y carros'],
  'encyclopedia.monsters': ['怪兽', 'Monsters', '괴수', 'Чудовища', 'モンスター', 'Monstruos'],
  'encyclopedia.artillery': ['炮兵与战争机器', 'Artillery & war machines', '포병 및 전쟁 기계', 'Артиллерия и боевые машины', '砲兵と戦闘機械', 'Artillería y máquinas de guerra'],
  'encyclopedia.other': ['其他', 'Other', '기타', 'Прочее', 'その他', 'Otros'],
}
